### ISSUE TITLE
Two or more agencies ?

### ISSUE THREAD

**Issue by wkulesza** [BlinkTagInc/gtfs-to-html#100]
Hi,
I was wondering if its possible to add two or more agencies in order to generate timetables from GTFS ?
I have an agency that operates in two adjoining regions - we produce two gtfs for them, each for the region but I would like to see them on one map with one list of routes.

**Comment by brendannee** [comment]
I just pushed version 1.4.1 which adds support for having more than one agency - you can  see how to specify this in the documentation here: https://gtfstohtml.com/docs/configuration#agencies

Let me know how this works for your use case.
