### ISSUE TITLE
[BUG] Multi-route timetable maps have no color differentiation

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/gtfs-to-html#103]
Hi! I seem to have found a bug in the latest version of GTFS-to-HTML (1.4.6)
# Issue
When creating multi-route timetables, all routes shown on the map take the `route_color` of the first route listed in `timetables.txt`
# Expected behavior
Each route is displayed on the map in the `route_color` defined for that particular route in gtfs.
# Reproduction steps
1. Use `GTFS-to-HTML` `v.1.4.6`
2. Place the contents of the [transcollines.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5718533/transcollines.zip) file into your `GTFS-to-HTML` directory. **DO NOT ALTER ANY FILE NAMES**
3. Run `GTFS-to-HTML` using `config-transcollines.json`
4. When GTFS-to-HTML has finished running, open the index and click the only available timetable page.
5. Look at the map.

Thanks for making these awesome tools!

**Comment by brendannee** [comment]
Thanks for the detailed report.

I fixed this issue in v1.4.7 - try it out and let me know if there are any other issues.

**Comment by brodyFlannigan** [comment]
That took care of it!
Thanks for the quick fix.
Closing issue :)
