### ISSUE TITLE
Mapbox alternative?

### ISSUE THREAD

**Issue by wkulesza** [BlinkTagInc/gtfs-to-html#107]
Hi,
I'm using this great tool to assist a small town public transport operator (struck by covid, like most of the agencies) and helping passengers see their limited services. We went above the free tier in mapbox - just for safety reasons (especially if pageloads grow too fast), I was wondering if there are alternatives to mapbox (i.e. self-hosted), that would allow not to use mapbox ?

**Comment by brendannee** [comment]
You could use something like https://openmaptiles.org to run  your own tileserver and leaflet.js or Mapbox GL JS for serving them.
