### ISSUE TITLE
gtfs-to-html not using more ram when set to

### ISSUE THREAD

**Issue by EnokiPPT** [BlinkTagInc/gtfs-to-html#112]
Hello,
I'm trying to convert a GTFS file that is rather large, but it doesn't seem to be using more memory when it's set to.
This is what I'm doing:
`[enoki@enoki-pc ~]$ node --max-old-space-size=1250 /usr/local/bin/gtfs-to-html/`
`[enoki@enoki-pc ~]$ /usr/local/bin/gtfs-to-html/bin/gtfs-to-html.js --configPath'/home/enoki/config.json' `
However, it's still just as slow.

**Comment by brendannee** [comment]
Thanks for the feedback.  The syntax for specifying max-old-space-size has changed (use an environment variable to ensure that all node processes get obey this directive):

`NODE_OPTIONS=--max_old_space_size=4096 gtfs-to-html --configPath'/home/enoki/config.json'`

**Comment by EnokiPPT** [comment]
> Thanks for the feedback. The syntax for specifying max-old-space-size has changed (use an environment variable to ensure that all node processes get obey this directive):
> 
> `NODE_OPTIONS=--max_old_space_size=4096 gtfs-to-html --configPath'/home/enoki/config.json'`

@brendannee Running this doesn't appear to make it run any faster.

**Comment by brendannee** [comment]
It won't make it faster, it will only prevent running out of memory.

**Comment by EnokiPPT** [comment]
Ah, so that was just a misconception on my part. Guess I'll wait the two hours it needs, but when I open it the map freezes everything on both Firefox and Chromium.

**Comment by brendannee** [comment]
If you want to limit which timetables are created, you can use timetables.txt to specify that it only build timetables for specific routes/directions/days of the week https://gtfstohtml.com/docs/timetables (use that while configuring and testing to try out all the settings)

You can turn off the map using https://gtfstohtml.com/docs/configuration#showmap to generate timetables without the map

What GTFS are you using?

**Comment by EnokiPPT** [comment]
> If you want to limit which timetables are created, you can use timetables.txt to specify that it only build timetables for specific routes/directions/days of the week https://gtfstohtml.com/docs/timetables (use that while configuring and testing to try out all the settings)
> 
> You can turn off the map using https://gtfstohtml.com/docs/configuration#showmap to generate timetables without the map
> 
> What GTFS are you using?

I'm doing it specifically with the map, it's RTD's (Denver) GTFS from October 2019.
I'll look into specifying which ones specifically.

**Comment by brendannee** [comment]
Yeah - you'll need to create a timetables.txt and add it to the existing GTFS files if you want to be able to control which routes/directions/days of the week get generated.

If you ONLY want the map, you can use https://www.npmjs.com/package/gtfs-to-geojson which is much more efficient as it doesn't generate timetables.

**Comment by EnokiPPT** [comment]
Only the map would actually be better, thank you for this!

**Comment by brendannee** [comment]
I tried running this GTFS https://www.rtd-denver.com/files/gtfs/google_transit.zip and it creates 1035 timetables (104 routes x 2 directions x 4-5 different day of the week schedules) - so if you don't want some days of the week schedules generated, creating timetables.txt would make it require a lot less time.
