### ISSUE TITLE
Map causes webpage to freeze, each route is listed 12 times.

### ISSUE THREAD

**Issue by EnokiPPT** [BlinkTagInc/gtfs-to-html#113]
Hello,
After figuring out the map I uploaded the HTML to https://rtd-archives.ga but it freezes my browser for a solid few minutes before working. All of the routes are also listed 12 times, and I think fixing the latter could help fix the former?
![not working](https://user-images.githubusercontent.com/52358711/115568707-69810780-a271-11eb-8634-64b390fe17f3.png)

**Comment by EnokiPPT** [comment]
Update: It's not just the GTFS file itself, trying it with other ones gives the same result. Will try it with a different transit operator.

**Comment by brendannee** [comment]
Try adding a timetables.txt and timetable_pages.txt files to the GTFS to control exactly which routes and days of the week timetables get generated for and to group them by route onto a single page. This will reduce the number of timetables being shown on the overview page to a reasonable number. 

https://gtfstohtml.com/docs/timetables
https://gtfstohtml.com/docs/timetable-pages

**Comment by EnokiPPT** [comment]
> Try adding a timetables.txt and timetable_pages.txt files to the GTFS to control exactly which routes and days of the week timetables get generated for and to group them by route onto a single page. This will reduce the number of timetables being shown on the overview page to a reasonable number.
> 
> https://gtfstohtml.com/docs/timetables
> https://gtfstohtml.com/docs/timetable-pages

This will take a very long time given the number of routes, I'll let you know what happens.

**Comment by brendannee** [comment]
Here is an example GTFS with timetables.txt and timetable_pages.txt added for reference: https://github.com/marintransit/marintransit-gtfs

It takes some work to configure, but it shouldn't change much going forward except if routes are added or removed.

**Comment by stevebab** [comment]
@EnokiPPT , to verify, @brendannee  is correct. For the best result, it is worth the time to create the extra timetables.txt files.
