### ISSUE TITLE
Internal server error on https://run.gtfstohtml.com/

### ISSUE THREAD

**Issue by stevebab** [BlinkTagInc/gtfs-to-html#116]
Just an fyi. Thank you for this very wonderful tool.

**Comment by brendannee** [comment]
Thanks for the heads up - it is back up now. https://run.gtfstohtml.com

**Comment by stevebab** [comment]
Hi Brendan,

Loving this tool. I am really blown away. Thank you for creating this!

I have two questions about the app at https://run.gtfstohtml.com

First, the individual tables generated don't include a map above the
timetable (although the showMap setting is true). I do get a map on the
overview page with all routes, though. I've read through the documentation
to see if there is an additional setting to get a map with each timetable,
but I can't seem to find that. Any suggestions?

Second, the zip download after generating files is empty (although the
zipOutput  is set to true). The aws hosted map site does work, however.

Very Respectfully,

*Steve Babbitt*
*Senior Developer*
***@***.***
(619) 757-1303  (tel)
(619) 828-0442  (fax)

*Mile3 Web Development*
*Interactive Web Site Design, Development and Management*
https://www.mile3.com

*Need support quickly? *
Send a message to ***@***.***
or call (619) 535-1932
for the fastest possible response.

**Comment by brendannee** [comment]
Can you let me know what GTFS file you are using so I can try it out? Also, link me to any output from the site so I can see what you are seeing.

**Comment by stevebab** [comment]
Please see attached.

Also, the url is
https://gtfs-to-html.s3.amazonaws.com/7f99ea06-0774-4d94-8454-5ac096c95945/index.html

Very Respectfully,

*Steve Babbitt*
*Senior Developer*
***@***.***
(619) 757-1303  (tel)
(619) 828-0442  (fax)

*Mile3 Web Development*
*Interactive Web Site Design, Development and Management*
https://www.mile3.com

*Need support quickly? *
Send a message to ***@***.***
or call (619) 535-1932
for the fastest possible response.

**Comment by brendannee** [comment]
I just deployed an update to http://run.gtfstohtml.com which should solve all of these issues. Try it out (add your own mapbox token to the config to ensure the maps will work for you).

Let me know if you see any other issues.

**Comment by stevebab** [comment]
Hi BRendan,

Good morning!  Getting a 502 bad gateway at https://run.gtfstohtml.com/

Very Respectfully,

*Steve Babbitt*
*Senior Developer*
***@***.***
(619) 757-1303  (tel)
(619) 828-0442  (fax)

*Mile3 Web Development*
*Interactive Web Site Design, Development and Management*
https://www.mile3.com

*Need support quickly? *
Send a message to ***@***.***
or call (619) 535-1932
for the fastest possible response.

**Comment by brendannee** [comment]
Just working out the kinks with the new version of the service - its back up now.

**Comment by stevebab** [comment]
You are very gracious Brennan. Thanks!

Very Respectfully,

*Steve Babbitt*
*Senior Developer*
***@***.***
(619) 757-1303  (tel)
(619) 828-0442  (fax)

*Mile3 Web Development*
*Interactive Web Site Design, Development and Management*
https://www.mile3.com

*Need support quickly? *
Send a message to ***@***.***
or call (619) 535-1932
for the fastest possible response.

**Comment by stevebab** [comment]
So close!  This is incredible.

A couple of issues:

1. The downloadable zipped file does not contain the js directory (with
system-map.js and timetable.js)
2. Still no maps on the actual route pages ... I'm using this file
http://96.126.103.89/google_transit_test20210623.zip and the json below:

{
  "allowEmptyTimetables": false,
  "beautify": true,
  "coordinatePrecision": 5,
  "dateFormat": "MMM D, YYYY",
  "daysShortStrings": [
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Sun"
  ],
  "daysStrings": [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
  ],
  "defaultOrientation": "vertical",
  "interpolatedStopSymbol": "•",
  "interpolatedStopText": "Estimated time of arrival",
  "linkStopUrls": true,
  "mapboxAccessToken":
"pk.eyJ1IjoibTNzdXBwb3J0IiwiYSI6ImNrZ2I5M3NxaDBlb2cyeXF1aGpvaWM5N3EifQ._Fd9Z30wR6hKcFFBbX_pFA",
  "menuType": "simple",
  "noDropoffSymbol": "‡",
  "noDropoffText": "No drop off available",
  "noHead": false,
  "noPickupSymbol": "**",
  "noPickupText": "No pickup available",
  "noServiceSymbol": "-",
  "noServiceText": "No service at this stop",
  "outputFormat": "html",
  "requestDropoffSymbol": "†",
  "requestDropoffText": "Must request drop off",
  "requestPickupSymbol": "***",
  "requestPickupText": "Request stop - call for pickup",
  "serviceNotProvidedOnText": "Service not provided on",
  "serviceProvidedOnText": "Service provided on",
  "showArrivalOnDifference": 0.2,
  "showMap": true,
  "showOnlyTimepoint": false,
  "showRouteTitle": true,
  "showStopCity": true,
  "showStopDescription": true,
  "sortingAlgorithm": "common",
  "timeFormat": "h:mma",
  "useParentStation": true,
  "zipOutput": true
}

Very Respectfully,

*Steve Babbitt*
*Senior Developer*
***@***.***
(619) 757-1303  (tel)
(619) 828-0442  (fax)

*Mile3 Web Development*
*Interactive Web Site Design, Development and Management*
https://www.mile3.com

*Need support quickly? *
Send a message to ***@***.***
or call (619) 535-1932
for the fastest possible response.

**Comment by brendannee** [comment]
Thanks for following up on this - I resolved the issue with the JS not showing up in the zip export.
