### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by AlbertoPimpo** [BlinkTagInc/gtfs-to-html#118]
I tried to write different docker files and built on different machines on different architectures but it seems it doesn't work. This is the last try I have done:

`FROM node:14

RUN npm install -g gtfs-to-html

EXPOSE 5000

CMD [ "gtfs-to-html" ]`

This should work but it doesn't. It could be very helpful to have an official dockerfile (or an official image). Thanks.

**Comment by brendannee** [comment]
This is a good idea - I played around and got docker working and added a Dockerfile to the repo: https://github.com/BlinkTagInc/gtfs-to-html/tree/master/docker

I also added documentation on how to make it work:

https://gtfstohtml.com/docs/quick-start#docker-usage

Try it out - feedback is welcome as are updates to the docker file to make it work better and documentation improvements to make it easier to understand how to use.
