### ISSUE TITLE
https://run.gtfstohtml.com/ not recognizing zipped archive

### ISSUE THREAD

**Issue by stevebab** [BlinkTagInc/gtfs-to-html#123]
Hi, had this issue before, but https://run.gtfstohtml.com/ seems to not allow me to use this zipped file:

http://96.126.103.89/google_transit_test20210623.zip

I think I'm doing it right, but not sure...

**Comment by brendannee** [comment]
Thanks for reporting this.

The zip file you linked to actually contains two folders, one called
google_transit_test20210623 and a hidden folder called __MACOSX.
GTFS-to-HTML throws an error if a zipfile has more than one subfolder as it
doesn't know which one to choose.

Can you try rezipping without the hidden folder and it should work.
