### ISSUE TITLE
feature request: symbol, stop time, both

### ISSUE THREAD

**Issue by ehowington** [BlinkTagInc/gtfs-to-html#125]
Idea for future consideration

Agencies have varying ways of describing pickup and drop off restrictions in their timetables:
1. Agency A: No request stops contain stop times, so only symbols are shown (eg, "REQ");
2. Agency B: All stops have times associated with them if serviced, and request stops also need to have the symbol associated with them (eg, "7:20pm REQ");
3. Agency C: All stops have times associated with them if serviced, but the symbol is the only thing that should show for request stops (eg, "REQ").

So you have two variables, stop time and pickup/drop off restriction, and agencies will desire to show one, or both, resulting in three possible options.

Putting aside the possibility of combos of pickup and drop off restrictions (G2H currently supports pickup_type and drop_off_type of 1 and 2, not 3), it would be hugely beneficial to be able to describe in the config the following:

Restrictions:
1. Show times unless there are symbols (this would work for both agency A and C)
2. Show times and symbols (this would work for agency B)

I would recommend lumping agency A and C together, since increasingly, agencies will be required to include stop times with all stops, even request stops, in facilitation of gtfs-rt/CAD/AVL software that requires each value in stop_times.txt contain a stop time. Additionally, in cases where the last stop of a trip is on demand, GTFS requires a last stop time, and if that is an estimate to ensure the data holds integrity, agencies do not want this shown as an actual stop time and wish to only show the REQ value.

The only use case I can think of where there could be utility in showing stop time *only* would be a route that is entirely on-demand, but contains a few helpful stops to indicate the general scope of the route (Victor Valley has had routes like this in the past.) I think if you wanted to account for that use case, a third option, "Show symbols unless there is a stop time."

cc @ekeaton @danielleogden

**Comment by brendannee** [comment]
Thanks for the detailed writeup.

Do you think a configuration parameter in config.json would be suitable to hide times? Something like `showStoptimesForRequestStops` with a default value of `true`?

* This would apply to all routes for an agency - are there many cases where an agency would want to apply this on a route-by-route or stop-by-stop basis?
* Can you think of a better parameter name?

Or should this be something configured in timetables.txt to allow it to take effect only for specific timetables?

Are there a lot of agencies you've seen where this feature would be useful?

Regardless of if you hide times from users in the HTML timetables, the times will be shown on google maps/Apple Maps. Does this mean that agencies just shouldn't hide times in timetables even if they want to?

As for the limited use case of showing stop times _only_, you can already do this by using a blank "" value for `requestDropoffSymbol` and `requestPickupSymbol`.
