### ISSUE TITLE
Invalid Mapbox access token

### ISSUE THREAD

**Issue by ekeaton** [BlinkTagInc/gtfs-to-html#129]
I've had success using the Mapbox access token noted here:https://gtfstohtml.com/docs/configuration#mapboxaccesstoken in the past. However, now I'm receiving this error in the console
<img width="1412" alt="Screen Shot 2021-12-22 at 12 26 58 PM" src="https://user-images.githubusercontent.com/43942870/147151662-8e2aa6db-b8a3-460b-b25e-4f8494957e84.png">

I'm using the sample-config attached. 
 
[config-sample.json.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/7765053/config-sample.json.zip)

**Comment by brendannee** [comment]
It looks like you need to get an updated mapbox token from mapbox.com, or disable maps entirely https://gtfstohtml.com/docs/configuration#showmap

**Comment by ekeaton** [comment]
Ah no, in this test case, I want it to show. But thanks that answers my question!
