### ISSUE TITLE
Continues as (in-seat transfer) with block_id

### ISSUE THREAD

**Issue by antrim** [BlinkTagInc/gtfs-to-html#13]
Possible enhancement: Option to use blocks for in-seat transfer information at the end/beginning of a trip?

**Comment by thomastrillium** [comment]
@brendannee an example here is the Routes 10/12/14 for Sonoma County Transit. In the currently live HTML timetables, we do not include the "Continues as" row, but if you compare the HTML to the live PDF, you'll see where the information should be included. 

http://sctransit.com/maps-schedules/route-12-route-14/

Note that this is also an example where timetable_pages are also relevant.

The GTFS was just updated today and current live timetables.txt information is just the "estimate" provided by our exporter. I'm going to spend the next couple minutes mocking up a timetables.txt and timetable_pages.txt that only has these 3 routes in it. Will that be sufficient to get you started? I probably can't have full timetables.txt until tomorrow but could rush it.

**Comment by thomastrillium** [comment]
Actually, I think the timetables.txt [at the fetch location](http://data.trilliumtransit.com/gtfs/sonomacounty-ca-us/sonomacounty-ca-us.zip) will work fine, although you may want to remove the timetable_stop_order.txt. I was wrong and timetable_pages really aren't at issue here.

But it's just the [route 10 timetables and the saturday route 12 timetable that are the relevant examples](http://sctransit.com/wp-content/transit-data/guides/SCT_Schedule_AUG2017_10-12-14.pdf) so to simplify, I've attached below a version of the gtfs that doesn't have timetable_stop_order.txt, and only has those 3 timetables in timetables.txt.

[sonomacounty-ca-us.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/2037309/sonomacounty-ca-us.zip)

**Comment by brendannee** [comment]
I have this working with GTFS-to-HTML (not published yet). I published Routes 10 and 12 so you can see how it looks and give feedback

https://sonoma-ljehxdgwtq.now.sh/

I'm planning to add an optional field to `timetables.txt` called `show_continuation` which is either 0 or 1, defaulting to 0 for not showing any continuation. @antrim @thomastrillium What do you think of that variable name?

Let me know what you think of the formatting. I updated both the horizontal and vertical timetable templates. If a route has a route_url, it is a link otherwise it will just be text.

**Comment by thomastrillium** [comment]
> show_continuation

maybe for consistency with real-life language, we call it `show_continues_as` but maybe that's just nitpicking and just as confusing.

**Comment by brendannee** [comment]
Great suggestion.

Currently the logic for getting the continues as:

* Take the block_id of the trip being shown.
* Search for all trips that have the same block_id, different route_id and the same service_ids as the timetable being rendered.
* Find the first stoptime's departure time for each of those trips
* Find the trip with the soonest first stoptime departure time after the trip being shown's last stoptime's arrival time.
* Get the route info for that trip

Some questions:
* Should the `continues_as` trip be required to have the same first stop_id as the previous trips last stop_id? Or are these sometimes different (the bus goes down the road a bit before starting as a new route, or two stop_ids which are effectively the same place but have different ids for some reason)?

* Can the `continues_as` trip have the exact same departure_time at the first stop as the previous trips arrival_time? Currently, I'm only looking for trips after the last stoptimes arrival_time, but maybe I should be considering trips equal to or greater than that time.

* Should we exclude `continues_as` trips if they are very far in the future, such as a route that continues on, but waits for 6 hours? If so, what should be the hard-coded value after which we shouldn't show routes continuing on?

* Would it be useful to show a `continued_from` field at the top of timetables to show what routes the vehicle was previously? Or does this just complicate things?

**Comment by thomastrillium** [comment]
> Should the continues_as trip be required to have the same first stop_id as the previous trips last stop_id?

I think so. This is in GTFS best practices so is a perfectly reasonable request to make. The situation you describe does happen sometimes, but shouldn't be how things are represented within the GTFS itself.

> Can the continues_as trip have the exact same departure_time at the first stop as the previous trips arrival_time?

Yeah, I think this should be > or =

> Should we exclude continues_as trips if they are very far in the future, such as a route that continues on, but waits for 6 hours? If so, what should be the hard-coded value after which we shouldn't show routes continuing on?

*hopefully* the blocks don't result in this, but you're totally right that they could. I'd propose some cut off like 15 or 30 minutes. My hunch is 15 would be safe, but that 30 would be more appropriately conservative.

> Would it be useful to show a continued_from field at the top of timetables to show what routes the vehicle was previously? Or does this just complicate things?

I have seen this before, but my feeling is that this would over complicate things.

**Comment by brendannee** [comment]
For the max wait time between "continues as" trips, I tried enforcing 30 minutes, but I found that with Sonoma's schedules, there are many trips in their print PDF which show continues as which are greater than 30 minutes: http://sctransit.com/wp-content/transit-data/guides/SCT_Schedule_AUG2017_10-12-14.pdf

* Route 12 weekday trip at 7:05 AM continues as route 10, 32 minutes after its last stoptime.
* Route 10 weekend trip at 10:50 AM continues as route 12, 41 minutes after its last stoptime.

Perhaps 60 minutes is safer max value?

Any other feedback before I publish this update to gtfs-to-html?

**Comment by thomastrillium** [comment]
Fair enough! 60 minutes sounds good.

No other feedback on my end!

**Comment by brendannee** [comment]
OK - updated and published as https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.14.0

Please try it out and open new issues with feedback.

**Comment by brendannee** [comment]
Actually give this version a try: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.14.1
