### ISSUE TITLE
Map not using all available space

### ISSUE THREAD

**Issue by fishe-tm** [BlinkTagInc/gtfs-to-html#146]
Hello!

When viewing the generated HTML file, the map that shows on the right that lets you view all of the routes seems to only use a small part of the available space. The mapbox info is at the bottom, showing that it's probably supposed to use all of the space?

I've tried using a different browser (tried both qutebrowser and firefox) as well as a different mapbox access token (a bit of a grasp at straws), but it didn't work.
An image of this issue is below.
![image](https://user-images.githubusercontent.com/52358711/181099096-d023ec4c-5474-478a-bb59-b6f490eb32f6.png)

**Comment by brendannee** [comment]
Thanks for the report - I pushed an updated version 2.4.2 that solves this.

https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/2.4.2

**Comment by fishe-tm** [comment]
@brendannee I pulled the new release and did a test run, I still seem to be having the same issue.

**Comment by brendannee** [comment]
The key is making sure whatever template you are using loads the tailwind script include in the header: https://github.com/BlinkTagInc/gtfs-to-html/blob/master/views/default/layout.pug#L11

So, if you copied the "default" template to make your own custom template, you'll need to update layout.pug.

**Comment by fishe-tm** [comment]
That was exactly the problem - I'd installed gtfs-to-html through npm and had forgotten to update the config to change `template-path` back to `views/default`

Things are working fully now, thanks so much for both the help and for creating this awesome tool!
