### ISSUE TITLE
Importing - calendar_dates.txt - No file found But file is actually present

### ISSUE THREAD

**Issue by mircolac** [BlinkTagInc/gtfs-to-html#147]
Hello

I'm trying to make this work with this gtfs

https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=solweb.tper.it&filename=gommagtfsbo&version=20221006&format=zip

Tper is an italian bus agency. The gtfs itself is pretty big and got just the essential tables

![image](https://user-images.githubusercontent.com/15798772/196652853-eebe898f-7700-4ac4-9b56-e490d7e57c60.png)

This is the result when I try to run it

![image](https://user-images.githubusercontent.com/15798772/196653028-26dc058f-c235-43a4-b378-a447d9707064.png)

![image](https://user-images.githubusercontent.com/15798772/196653095-99ffaa5e-84fd-467a-b27e-24d696b63598.png)

I was able to launch gtfs-to-html with the sample config file (the 'bart' agency') so something tells me there's something wrong with the gtfs itself. 

I didn't do any particular change from the sample config file, except deleting the sqllite path and changing the url keyword with the path (since i'm using the already downloaded .zip)

any help is appreciated :)

**Comment by mircolac** [comment]
It worked :) Thank you so much!

The next problem i'm facing is that the process is taking too much time. 

I'm afraid it is due to the large number of records in the stop-times.txt file and probably there's not much to do about it...

![image](https://user-images.githubusercontent.com/15798772/197201949-d25da6d3-55d3-4407-928f-7c21d146f6ee.png)

Do you think there's something to do about it or should I just leave it for a day or two?

**Comment by brendannee** [comment]
You can add a timetables.txt file to the GTFS to control exactly which timetables get generated and greatly speed up the process.  https://gtfstohtml.com/docs/timetables

You can generate only one timetable for one route/direction/day combination if you want.

**Comment by mircolac** [comment]
Thank you! It worked!
