### ISSUE TITLE
Show service dates on the timetable

### ISSUE THREAD

**Issue by huyngd** [BlinkTagInc/gtfs-to-html#155]
Hello,

I have successfully generated a timetable here: https://huyngd.github.io/amsterdam-airport-express/

I am wondering:

(1) if there is a way to show the service dates on the table, since it only shows the days of week as of now.

(2) is there a way to group the trips belong to the same group together instead of showing all in one page like it is right now?

Please help me with this if possible. Much appreciated!

**Comment by brendannee** [comment]
You can better control exactly what dates timetables get created for and how they are named and group by adding a timetables.txt and timetable_pages.txt to your GTFS before processing it: https://gtfstohtml.com/docs/timetables - try this out and let me know if you hit any limitations.
