### ISSUE TITLE
Error: Cannot open database because the directory does not exist

### ISSUE THREAD

**Issue by Flopris** [BlinkTagInc/gtfs-to-html#156]
This is my first experiece experimenting with node and I am really lost on what to do.

I keep getting the error Error: Cannot open database because the directory does not exist, even when I test with the same settings from the sample config in my actual config.

Im probably making a very simple mistake somwhere but i just cannot find it.

C:\WINDOWS\system32>gtfs-to-html --configPath "\Users\Floris Vink\OneDrive\Documenten\Uni Dingen (PC)\2023\P1\NE\config.json"

Error: Cannot open database because the directory does not exist
[  Error: Cannot open database because the directory does not exist
]

**Comment by brendannee** [comment]
Can you share with me your config.json file?

**Comment by Flopris** [comment]
The config i'd like to use:

{
  "agencies": [
    {
      "agency_key": "TGV",
      "url": "https://eu.ftp.opendatasoft.com/sncf/gtfs/export_gtfs_voyages.zip"
    }
  ],
  "sqlitePath": "/tmp/gtfs",
  "allowEmptyTimetables": false,
  "beautify": false,
  "coordinatePrecision": 5,
  "dateFormat": "MMM D, YYYY",
  "daysShortStrings": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  "daysStrings": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
  "defaultOrientation": "vertical",
  "effectiveDate": "July 8, 2016",
  "interpolatedStopSymbol": "•",
  "interpolatedStopText": "Estimated time of arrival",
  "linkStopUrls": true,
  "mapboxAccessToken": "YOUR MAPBOX ACCESS TOKEN",
  "menuType": "simple",
  "noDropoffSymbol": "‡",
  "noDropoffText": "No drop off available",
  "noHead": false,
  "noPickupSymbol": "**",
  "noPickupText": "No pickup available",
  "noServiceSymbol": "—",
  "noServiceText": "No service at this stop",
  "outputFormat": "html",
  "requestDropoffSymbol": "†",
  "requestDropoffText": "Must request drop off",
  "requestPickupSymbol": "***",
  "requestPickupText": "Request stop - call for pickup",
  "serviceNotProvidedOnText": "Service not provided on",
  "serviceProvidedOnText": "Service provided on",
  "showArrivalOnDifference": 0.2,
  "showMap": true,
  "showOnlyTimepoint": true,
  "showRouteTitle": true,
  "showStopCity": false,
  "showStopDescription": false,
  "showStoptimesForRequestStops": true,
  "skipImport": false,
  "sortingAlgorithm": "common",
  "templatePath": "views/default",
  "timeFormat": "h:mma",
  "useParentStation": true,
  "verbose": true,
  "zipOutput": false
}


The sample config renamed to config i tried for troubleshooting, resulting in the same error.

{
  "agencies": [
    {
      "agency_key": "bart",
      "url": "http://www.bart.gov/dev/schedules/google_transit.zip"
    }
  ],
  "sqlitePath": "/tmp/gtfs",
  "allowEmptyTimetables": false,
  "beautify": false,
  "coordinatePrecision": 5,
  "dateFormat": "MMM D, YYYY",
  "daysShortStrings": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  "daysStrings": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
  "defaultOrientation": "vertical",
  "effectiveDate": "July 8, 2016",
  "interpolatedStopSymbol": "•",
  "interpolatedStopText": "Estimated time of arrival",
  "linkStopUrls": true,
  "mapboxAccessToken": "YOUR MAPBOX ACCESS TOKEN",
  "menuType": "simple",
  "noDropoffSymbol": "‡",
  "noDropoffText": "No drop off available",
  "noHead": false,
  "noPickupSymbol": "**",
  "noPickupText": "No pickup available",
  "noServiceSymbol": "—",
  "noServiceText": "No service at this stop",
  "outputFormat": "html",
  "requestDropoffSymbol": "†",
  "requestDropoffText": "Must request drop off",
  "requestPickupSymbol": "***",
  "requestPickupText": "Request stop - call for pickup",
  "serviceNotProvidedOnText": "Service not provided on",
  "serviceProvidedOnText": "Service provided on",
  "showArrivalOnDifference": 0.2,
  "showMap": true,
  "showOnlyTimepoint": false,
  "showRouteTitle": true,
  "showStopCity": false,
  "showStopDescription": false,
  "showStoptimesForRequestStops": true,
  "skipImport": false,
  "sortingAlgorithm": "common",
  "templatePath": "views/default",
  "timeFormat": "h:mma",
  "useParentStation": true,
  "verbose": true,
  "zipOutput": false,
  "debug": true
}

**Comment by brendannee** [comment]
Try omitting `sqlitePath` from the config - this will cause it to use an in-memory database.

Otherwise, change `sqlitePath` to a path that exists on your system, such as `\Users\Floris Vink\OneDrive\Documenten\Uni Dingen (PC)\2023\P1\NE\`

**Comment by Flopris** [comment]
I apllied the first step and that defenitly made it work. Im getting a lot of errors tho, but i think thats because this file has a decent chunk of missing data. Its a large file so I'll respond when its done and see if its actually working or not.

Thanks for the help.

**Comment by Flopris** [comment]
okay it finished with the following error messasge 

```
Error: ENOENT: no such file or directory, open 'views\default\overview_full.pug'
[  Error: no such file or directory, open 'views\default\overview_full.pug'
] {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'views\\default\\overview_full.pug'
}

``` 

Trying to connect to localhost 3000 shows it cant be reached

**Comment by brendannee** [comment]
Try removing the `templatePath` field from your config.json.

**Comment by Flopris** [comment]
> Try removing the `templatePath` field from your config.json.

That seems to have done it, its going now without anu warnings.

 Its even slower than before tho and when I tried to assign more memory earlier i got more errors, something about the module not being present. But thats an issue for another time, I just hope this works now when i check up on it next morning. 

Thanks a lot for these quick replies.
