### ISSUE TITLE
Uploading GTFS file to the web version

### ISSUE THREAD

**Issue by FreshTaco1** [BlinkTagInc/gtfs-to-html#157]
Hi there, 

Is there the ability to upload a GTFS zip file to the web version of your tool?

Thanks

**Comment by brendannee** [comment]
Not currently - it is currently setup to only support downloading from a URL.  

I may add this feature in the future - for now you'll need to upload it to a URL, or use GTFS-to-HTML locally.

**Comment by FreshTaco1** [comment]
Just one follow up. Do you know of any methods or online storage where I could have the GTFS file and then link it to your tool? I tried Google Drive but no luck there. Does it need to be a public environment? Thanks

**Comment by brendannee** [comment]
It does need to be public so the server can fetch it - you could try dropbox and add a dl=1 query parameter to the URL: https://help.dropbox.com/share/force-download

**Comment by FreshTaco1** [comment]
That worked. Thank you!
