### ISSUE TITLE
Specifying start point and only including certain stops

### ISSUE THREAD

**Issue by FreshTaco1** [BlinkTagInc/gtfs-to-html#158]
Hi there,

Hopefully I havent missed this in the configuration guidance. Using the web version while I am at work and going to try using the desktop version on my personal laptop (security limiations on a work laptop). But is there a way to specify the timetable start point? Currently when loading in the GTFS file it starts at 9:00am even when the first run kicks off at 6:20. 

Also, is there a way so it only includes certain stops? 

Thanks

**Comment by brendannee** [comment]
Hi,

Can you share with me the GTFS you are using and which route/direction has the issue of the timetable starting at 9 AM and missing trips before this?

**Comment by FreshTaco1** [comment]
Actually, scratch that. I was an idiot and didn't realise that the route i was looking at has been broken up based on it having multiple route id's. So, I will need to look at the multiple timetable info you provided in additional GTFS files on your website. But on the note of only including certain stops, is that possible through the web-based version?
Thanks

**Comment by brendannee** [comment]
If you want to include only stops that are timepoints, you can control that using the configuration option in the web-based version.

If you want to manually specify which stops are included, you can do that by including timetables.txt and timetable_stop_order.txt in the GTFS that is specified in the web-based version.
