### ISSUE TITLE
Missing tables on same timetable_page_id although listed in `timetables.txt`

### ISSUE THREAD

**Issue by rcst** [BlinkTagInc/gtfs-to-html#160]
Hello,

first of, thanks for this very valuable Software!

I have a schedule (see attached) that is split for most routes into "seasons", e.g. for route_id = 1

- 20240101 to 20240630 ... called "before summer"
- 20240701 to 20240831 ... called "summer"
- 20240901 to 20241231 ... called "after summer" 

(all in Albanian language).

When I render the timetables, only the "before summer" tables are produced, although respective entries for "after summer" are listed in timetables.txt (see attached). In addition, only weekends for summer are listed. I would have expected to see 16 tables on page_id = 1 (= route_id) as listed in timetables.txt

Perhaps, someone can clarify, I'm suspect I'm misunderstanding the way trips and services are summarized.

Best regards

[gtfs.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/14775739/gtfs.zip)

**Comment by brendannee** [comment]
Thanks for the detailed info.

I tried running the GTFS you sent and found that the timetable for route 1A which is timetable_page_id = 1 did generate all 16 timetables in one HTML file, including timetables for weekends and different calendars. 

Attached is the output I got - does this match the output you got?
[mot.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/14784408/mot.zip)

Let me know if the timetables attached missed anything.

**Comment by rcst** [comment]
Thank you for this swift response.

Indeed, your output contains the tables as expected. Now, I've missed to mentioned that I altered the standard configuration, amonst others `menuType: "radio"`. I'm attaching my configuration file. I'm running `gtfs-to-html` as a docker container. Perhaps, I've misconfigured it, may I ask you to verify my configuration? With the radio menue, I'm only seeing a single table for each active choice, where I would expect to see a *list* for tables for each choice. Hence, I'm attaching too the output I generated. For completeness, I've made minor changes in some of the *.pug files (I've removed the "Run #X" headers).

[mot.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/14788323/mot.zip)
[config.json](https://github.com/BlinkTagInc/gtfs-to-html/files/14788325/config.json)
[views.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/14788355/views.zip)

**Comment by brendannee** [comment]
The "radio" menu type requires some javascript in order to function. It shows only one timetable at a time, and you click the buttons. 

You can see the JS needed here: https://github.com/BlinkTagInc/gtfs-to-html/blob/master/public/js/timetable-menu.js#L7 (also requires jquery). You could instead write your own js to handle showing/hiding timetables on click and include it as part of your custom template.

Attached is the output I got when I tried the config.json and custom view template you sent.
[mot.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/14794175/mot.zip)
