### ISSUE TITLE
Noob: Is there a way to filter only given line(s) or zones?

### ISSUE THREAD

**Issue by eMerzh** [BlinkTagInc/gtfs-to-html#161]
Hello 👋 

This project looks amazing 👏  well done.

I was just frustrated by my local network not giving proper info on their app, 
but provide RT info of some buses throught GoogleMap.

Long story short, i got access to the GTFS file as well as RT feeds & stuff.
I found this project (and the other linked) and i'm currently exploring 

i started by ref
```json
{
  "agencies": [
    {
      "agency_key": "TEC",
      "url": "https://opendata.tec-wl.be/Current%20GTFS/TEC-GTFS.zip"
    }
  ]
 }
```
and launching the command, but the result : 

>TEC: Generating HTML timetables ---------------------------------------- 5435/635894

like 😱 

it seems there are a lot of day/lines possibility or something.. it will take forever 😬 ...

so i was wondering if there was (or can i ask for it 😇 ) a way to filter by a given line, or stop or 🤷 

this would help the initial setup, (like no need to generate 635894 files to throw them all away) but could also limit the need to recompute everything for example

(note: the generation clear the generate directory every few hundred tasks , but it might be a config issue 🤔 )

**Comment by eMerzh** [comment]
@brendannee thanks a lot for your quick reply :) 
so the idea is that i download the static zip... add my timetables.txt file in there, and then rezip it an generate the thing from there?

**Comment by brendannee** [comment]
Yes - but no need to rezip - you can just point gtfs-to-html to the path of the unzipped GTFS.
