### ISSUE TITLE
[Suggestion] Allow HTML formatting in timetable notes

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/gtfs-to-html#162]
Currently, timetable notes are in plain text, which works well for a lot of simple applications.

We at Transcollines provide users with information in both French and English.

Currently, we just provide both languages in a single note, with the French and English separated by a slash. The result is rather unflattering, especially when we put in particularily long notes.

What we'd like to be able to do is add HTML formatting tags to the notes such as `<br>` and `<i>` to better distinguish the two languages. Having this ability would also allow us to add hyperlinks in footnotes to direct users to holiday service information, for instance.

I'd like to see what others think of this idea...

**Comment by brendannee** [comment]
Support for at least some HTML seems like a good idea.

What about allowing markdown format in notes and then having GTFS-to-HTML render that to HTML?

**Comment by brodyFlannigan** [comment]
I hadn't thought of markdown. That's a great idea.

**Comment by brendannee** [comment]
I added markdown support in timetable_notes in the latest release: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/2.6.2 try it out and let me know what you think and if you have any other ideas.

**Comment by brodyFlannigan** [comment]
This is awesome. Thank you SO MUCH for this.

The timetables look great.
