### ISSUE TITLE
not compatible with gtfs 4.13.3+?

### ISSUE THREAD

**Issue by zkiiito** [BlinkTagInc/gtfs-to-html#168]
i've just upgraded to 2.7 and it also upgraded gtfs to the latest (4.13.4). when i generate the timetable with map, it does not display the route on the timetable page, just the stops.
when i downgraded gtfs to 4.13.2 it worked fine.

when i did a diff on the generated timetable files, the main difference was that this object was empty with the latest gtfs:
```
              "geojson": {
                "type": "FeatureCollection",
                "features": [{
```

filled with data on 4.13.2
```
                "features": [{
                  "type": "Feature",
                  "properties": {
                    "route_color": "#256dbb"
                  },
                  "geometry": {
                    "type": "LineString",
                    "coordinates": [
                      [19.08697, 47.36039],
                      ...
```

**Comment by brendannee** [comment]
Thanks for reporting this issue - can you share a link to the GTFS you are using so I can recreate the issue?

**Comment by brendannee** [comment]
I found the issue that you mentioned and published an updated version that should resolve it: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/2.7.1 

Try it out and let me know if there are any other issues you notice.

**Comment by zkiiito** [comment]
now it works perfectly, thanks!
