### ISSUE TITLE
GTFS-RT support doesn't appear to be working

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/gtfs-to-html#172]
Hi!

I can't seem to get the GTFS-RT functionnalities to work in GTFS-to-HTML...

I've tried several GTFS and GTFS-RT sources, and even though I can see the GTFS-RT endpoints being called in the browser console, I'm not seeing the vehicles on the map or the updated arrival times.

I'm also not seeing any errors in the console or anywhere else for that matter that would indicate an issue with the GTFS-RT handling.

Here is my [config.json](https://github.com/user-attachments/files/16918594/config_nomapbox.json) (with the Mapbox key removed for obvious reasons).

I'm using an unmodified install of the latest version of GTFS-to-HTML.

Could you look into this?

**Comment by brendannee** [comment]
Thanks for reporting this - I'll take a look and let you know what I find.

**Comment by brendannee** [comment]
Hi,

I pushed a few updates that improve the GTFS-realtime features of GTFS-to-HTML - try again with the latest version https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/2.9.6

I tested it with your config.json and did see vehicles showing up on the map now. 

Try it out and let me know what feedback you have.

**Comment by brodyFlannigan** [comment]
Hi!

So the issue with the positions not showing up has been resolved.

However, I've encountered a new issue with fetching real-time data.

It seems that when not all three of the RT feed URLs are provided in the configuration, some of the RT feeds aren't being fetched...

I'm using the latest release (2.9.9).

Here's what I've been observing using the config-default-full, and adding/removing the different RT URLs:

| **RT URLs provided** | **TripUpdates Fetch** | **VehiclePositions Fetch** | **Service Alerts Fetch** |
|---|---|---|---|
| TU+VP+SA | ✅ | ✅ | ✅ |
| TU+SA | ❌ | N/A | ❌ |
| TU+VP | ✅ | ✅ | N/A |
| VP+SA | N/A | ❌ | ✅ |
| TU only | ❌ | N/A | N/A |
| VP only | N/A | ❌ | N/A |
| SA only | N/A | N/A | ❌ |

When I say feeds aren't being fetched, I mean that the request simply isn't being made. When looking at the network tab of the browser dev tools, I'm simply not seeing requests to the RT feeds.
The expected behaviour would be that any provided feed should be fetched.

Could you take a look at this?

**Comment by brendannee** [comment]
Thanks for the detailed tests.

I pushed an update which should resolve this: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/2.9.10

* Alerts will always be fetched if a URL is provided
* Vehicles positions will always be fetched if a URL is provided AND showMap config option is set to true
* Trip updates will be fetched only if a trip updates URL is provided AND a vehicle positions URL is provided AND showMap config option is set to true 

Trip updates are currently only used in the popup on vehicle pins, so they are not needed if there is no vehicle positions URL.  This could change if I update the map to show trip updates when clicking on a stop.

Try it out and let me know what you think.

**Comment by brendannee** [comment]
Closing this issue - let me know if the latest version didn't resolve this issue for you.
