### ISSUE TITLE
Discussion/idea: hourly schedule (minutes after the hour)

### ISSUE THREAD

**Issue by antrim** [BlinkTagInc/gtfs-to-html#31]
This is a common way of publishing hourly schedules:
http://eurekatransit.org/schedules/ets_weekday_Mar_2013.html

Times at stops are expressed as minutes after the hour. 

![red route 1](https://cloud.githubusercontent.com/assets/6495639/26515687/11667722-4232-11e7-8be2-b4a6c6826c92.png)

![red route 2](https://cloud.githubusercontent.com/assets/6495639/26515689/1824e0bc-4232-11e7-9fe8-cb1f8e381dfe.png)

Could GTFS-to-HTML be adapted to offer this as an output option?

**Comment by brendannee** [comment]
Interesting. I haven't seen agencies with routes like this before. Is Eureka Transit a good example of an agency with routes that only run once per hour at the exact same time each hour?

I can add this functionality to GTFS-to-HTML.

Would this likely be something you'd want to configure on a per-route basis, or are there a lot of agencies with 100% of their routes running hourly?

**Comment by antrim** [comment]
I think both situations are common: all routes for an agency are hourly (same minutes past the hour) as well as some routes.

Examples:

- Butte Bus: http://buttebus.org/schedules/oregon-racetrack-red/
- AMRTS in Arcata: http://www.arcatatransit.org/schedules/amrts_schedule.php?service=weekday
- Mountain Line in Flagstaff, AZ: http://mountainline.az.gov/routes/route-2-blue/ (This one is a bit complicated)

There are also many services that present a full timetable, that I think would actually be well served by a minutes-after-hour timetable:
- http://eldoradotransit.com/routes/cameron-park/
- http://redwoodcoasttransit.org/routes-schedules/route-1/

I'd suggest that this can be activated on a route-by-route basis, and that the timetable should just include the content of routes.route_desc to describe operating hours. It seems like first/last bus and span and frequency might all be troublesome to automatically determine and present (maybe set an ambition to add some of that later).

**Comment by antrim** [comment]
It's also an open question whether this would just be available for services defined with frequencies.txt or whether it would be possible to offer this for schedules defined by individual trips. Would there be a difference in effort to implement?

**Comment by antrim** [comment]
I think this is something that Trillium is going to want to use! Is this a feature that could be implemented? Would it be easiest to implement only if a route is described using frequencies.txt or does it matter?

**Comment by brendannee** [comment]
I added support for hourly timetables.

You can specify this on a per-route basis by setting the `orientation` value to `hourly` in `timetables.txt`.

I tested this with Butte Bus routes - here is an example
![hourly-timetable](https://user-images.githubusercontent.com/96217/27475322-968494ec-57b9-11e7-8c75-fc80f57737ab.png)

Note that if you use the`hourly` option with a route that isn't actually hourly, the timetable generated won't be accurate (it just grabs the times from the first trip, ignoring times on all later trips).

Let me know what you think and what else needs to be done to make this a useful feature.

**Comment by brendannee** [comment]
Closing this issue - please let me know if this feature needs any additional work.
