### ISSUE TITLE
Discussion: Legend

### ISSUE THREAD

**Issue by antrim** [BlinkTagInc/gtfs-to-html#35]
Should we add an option to output a legend that explains symbols? This could also be made part of #34 .

**Comment by brendannee** [comment]
Sure - can you give me more details. Do you mean only symbols in the timetable, or for the optional mapbox map as well? This should be pretty easy to add, but I'd want to see some example agencies with different needs to figure out how to best do this.

**Comment by brendannee** [comment]
@antrim Just following up on this - can you give me more info about the legend you had in mind?

**Comment by antrim** [comment]
Is there already a legend that is outputted?

If they are presented in the timetable, I was imagining a legend with:

* noServiceSymbol
* requestStopSymbol

How does GTFS-to-HTML currently represent stops with service but without a time specified?

Also related to #34 ("footnotes"), here is an example where we are adding symbols (post-processing after GTFS-to-HTML): https://juneaucapitaltransit.org/routes/mendenhall_loop_counterclockwise/

**Comment by brendannee** [comment]
There is already text that is outputted at the bottom of each timetable. It varies depending on the timetable - only the relevant symbols are shown for each timetable.

I added support (see latest master branch) for an `interpolatedStopSymbol` set to a default of `•`.

The other two symbols that can show up depending on the timetable are the `noServiceSymbol` and `requestStopSymbol` - all can be specified in config.json.

Here is a screenshot of a timetable with interpolated stops:

<img width="1258" alt="screen shot 2017-08-25 at 12 44 20 pm" src="https://user-images.githubusercontent.com/96217/29730185-06f375f2-8994-11e7-8260-ce52033ecd7a.png">

* What do you think of the name `interpolatedStopSymbol`?
* What do you think of the text shown for each of these symbols in the legend?
  *** = Request stop - call for pickup
  - = No service at this timepoint
  • = Vehicle may stop at these locations, in addition to the timed stops

**Comment by antrim** [comment]
Reactions/ideas below. Let me know what you think.

> * What do you think of the name `interpolatedStopSymbol`?

I think it's good.

> * What do you think of the text shown for each of these symbols in the legend?
>   *** = Request stop - call for pickup

Looks good.

>   - = No service at this timepoint

"No service at this stop"

"timepoint" -> "stop" (because not all stops will necessarily be timepoints)

>   • = Vehicle may stop at these locations, in addition to the timed stops

-> "Vehicle will serve stop between adjacent timed stops"

**Comment by brendannee** [comment]
Great suggestions - I updated the legend and published the changes (including improved logic for showing interpolated stops to version 0.12.4
