### ISSUE TITLE
Requested option: Stop Codes in separate column

### ISSUE THREAD

**Issue by hkvlhm** [BlinkTagInc/gtfs-to-html#38]
We'd like to have the option of displaying stop_codes in their own column to the right of the stop name, rather than under the stop name.

Let me know if it's not clear what I mean.

**Comment by brendannee** [comment]
You can currently do this using custom templates.

Add a `templatePath` to your config.json file like 

    "templatePath": "views/custom/stopcode/timetablepage_full.pug"

Then add the .pug files from [here](https://github.com/BlinkTagInc/gtfs-to-html/files/1216456/stopcode.zip) to `views/custom/stopcode`. (the zip file linked is a copy of the default templates with a new column for Stop Code.

Does this achieve what you wanted to do?

If you think that a lot of agencies would like stop code as a separate columnn, I could add this as a config option and update the default template to accept this. If its more of a one-off thing - then custom templating might be the best option.

**Comment by brendannee** [comment]
@hkvlhm Just checking if this method worked for you or if you have any other ideas.

Note that the current version on the master branch requires the path to the folder containing templates, so 

    "templatePath": "views/custom/stopcode/"

**Comment by hkvlhm** [comment]
Hi Brendan, sorry it's taken me so long to get back to this.

This doesn't seem to be working because views/custom/stopcode doesn't include overview.pug and overview_full.pug. Could you please advise?

**Comment by brendannee** [comment]
There have been a lot of changes to the way templates work since I posted that answer. Here is an updated set of templates, with modifications made to `timetable_horizontal.pug` to add a stop code column. 
[stopcode.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/1300765/stopcode.zip)

**Comment by hkvlhm** [comment]
Thanks! This works great. The stop codes are still included in the stop name column, as well as the new stop code column. Is this intentional?

**Comment by brendannee** [comment]
No, these could be removed. Do you want me to make an updated template?

**Comment by hkvlhm** [comment]
Yeah, that would be helpful. And I think using the templates accomplishes what I need, so adding it as a congif option doesn't seem necessary. Thanks for you help.

**Comment by brendannee** [comment]
See attached
[stopcode.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/1307668/stopcode.zip)

**Comment by evantrillium** [comment]
@brendannee I would like to use this template for NWOTA but am getting the following error
![Screen Shot 2019-09-10 at 2 48 16 PM](https://user-images.githubusercontent.com/31700284/64653034-2fcff580-d3da-11e9-8490-1e333b77d05d.png)

[config.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/3597834/config.txt)
/var/www/vhosts/oregon-gtfs.com/gtfs_data/tillamook-or-us/tillamook-or-us.zip

**Comment by evantrillium** [comment]
NWOTA: Generating HTML timetables [--------------------------------------] 0/38
Error: TypeError: views/custom/Stop_Code/timetablepage.pug:51
    49|               .note= `${config.interpolatedStopSymbol} = Vehicle will serve stop between adjacent timed stops`
    50| 
  > 51|         if timetable.specialDates.includedDates.length
    52|           .col-md-4
    53|             .included-dates Service provided on:&nbsp;
    54|               span= timetable.specialDates.includedDates.join(', ')

Cannot read property 'includedDates' of undefined
{ TypeError: views/custom/Stop_Code/timetablepage.pug:51
    49|               .note= `${config.interpolatedStopSymbol} = Vehicle will serve stop between adjacent timed stops`
    50| 
  > 51|         if timetable.specialDates.includedDates.length
    52|           .col-md-4
    53|             .included-dates Service provided on:&nbsp;
    54|               span= timetable.specialDates.includedDates.join(', ')

Cannot read property 'includedDates' of undefined
    at eval (eval at wrap (/usr/local/lib/node_modules/gtfs-to-html/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1063:28)
    at eval (eval at wrap (/usr/local/lib/node_modules/gtfs-to-html/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1883:4)
    at template (eval at wrap (/usr/local/lib/node_modules/gtfs-to-html/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1885:49)
    at Object.exports.renderFile (/usr/local/lib/node_modules/gtfs-to-html/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/usr/local/lib/node_modules/gtfs-to-html/lib/file-utils.js:97:24)
    at Object.exports.generateHTML (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:1047:32)
    at Promise.all.config.agencies.map (/usr/local/lib/node_modules/gtfs-to-html/lib/gtfs-to-html.js:76:35) path: 'views/custom/Stop_Code/timetablepage.pug' }

**Comment by brendannee** [comment]
Great question.

The latest version of GTFS-to-HTML changed the variable names from `timetable.specialDates.includedDates` to `timetable.calendarDates.includedDates`.

See the latest version timetablepage.pug https://github.com/BlinkTagInc/gtfs-to-html/blob/master/views/timetable/timetablepage.pug
