### ISSUE TITLE
Open thread: refine how days-of-service are indicated

### ISSUE THREAD

**Issue by antrim** [BlinkTagInc/gtfs-to-html#4]
**Proposal:** The days of week summary (e.g. Mon-Fri) that appears at the top of the timetable should be inclusive of all days that transit service operates.

**Issue:** We currently see a different behavior with some YARTS timetables (http://transitfeeds.com/p/yosemite-area-regional-transportation-system/155, 12-Oct-2015). Screenshot below. Note that this timetable encompasses service periods for different months, which is somewhat unusual.

**Alternative:** We could choose to produce these timetables differently, and choose a more standard approach where we split into separate timetables for distinct parts of the season. Currently, we are just trying to match their approach with the printed timetables.

<img width="712" alt="timetable for 120e-395" src="https://cloud.githubusercontent.com/assets/6495639/10438246/6527a282-70e7-11e5-8a63-257c437486b2.png">
#### excerpt from calendar.txt

| service_id | service_name | monday | tuesday | wednesday | thursday | friday | saturday | sunday | start_date | end_date |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 781A4094 | Hwy 120/395 - July/Aug 2014 (Mon-Sun) | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 20160701 | 20160831 |
| 782A4091 | Hwy 120/395 - June&Sept 2014 (Sat-Sun) | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 20160601 | 20170928 |
#### excerpt from timetables.txt

| timetable_id | route_id | direction_id | start_date | end_date | monday | tuesday | wednesday | thursday | friday | saturday | sunday | route_label | service_notes | direction_label |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 12 | 582 | 0 | 20160601 | 20170928 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | Mammoth Lakes HWY 120E-395 | Hwy 120-395 - June&Sept 2014 | Outbound |
| 13 | 582 | 1 | 20160601 | 20170928 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | Mammoth Lakes HWY 120E-395 | Hwy 120-395 - June&Sept 2014 | Inbound |
| 14 | 582 | 0 | 20160701 | 20160831 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | Mammoth Lakes HWY 120E-395 | Hwy 120-395 - July-Aug 2014 | Outbound |
| 15 | 582 | 1 | 20160701 | 20160831 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | Mammoth Lakes HWY 120E-395 | Hwy 120-395 - July-Aug 2014 | Inbound |

**Comment by aaronantrim** [comment]
This is non-urgent -- just documenting how this works currently.

**Comment by brendannee** [comment]
I could update the code so that it looks at all trips for a route, checks if any have different days of the week and different service period and creates route headers with days if there are. Or, we could add a `timetable_trips.txt` file that specifies which trips should be shown, which would better help you specify the order (in case it is difficult to determine programmatically which should be shown.

If this is something you still want, link me a GTFS file where this is applicable and an example of how the generated timetable should look.

**Comment by brendannee** [comment]
Closing this issue as it is old. If this is still something you are interested in discussing, feel free to reopen.
