### ISSUE TITLE
Automatically generated timetables contain all services in one timetable

### ISSUE THREAD

**Issue by nselikoff** [BlinkTagInc/gtfs-to-html#41]
When the timetables are automatically generated (i.e. no use of timetables.txt, timetable_pages.txt, etc), all days / service patterns are included in one timetable. If a route has different service on weekdays, Saturdays, and Sundays (for example), this can lead to what appears to be duplicate data in the table.

Example feed exhibiting this behavior:

```
  "agencies": [
    {
      "agency_key": "lynx",
      "url": "https://transitfeeds.com/p/central-florida-regional-transportation-authority/373/latest/download"
    }
  ],
```

**Comment by brendannee** [comment]
My thinking was that if you need to specify days for timetable generation, then you have to include the extra files. But, it would be possible to automatically detect days of the week and generate timetables accordingly which would make it work better out of the box for more agencies.

**Comment by brendannee** [comment]
I pushed an update that detects different service days for GTFS without timetables*.txt.

Check out 0.12.3 and let me know what you think.

**Comment by nselikoff** [comment]
Hmm I just tried the latest with the example above (lynx), without any timetables*.txt, and no timetables were generated. I cleared the db just in case.

**Comment by brendannee** [comment]
I just tried with the code from the master branch with https://transitfeeds.com/p/central-florida-regional-transportation-authority/373/latest/download and it generated 384 timetables.

Can you let me know what output you get?

**Comment by nselikoff** [comment]
My bad - it's working after running `npm install`. Generating now...

**Comment by nselikoff** [comment]
This is much better. Thank you! I think it's great to have a more accurate and comprehensive default list of generated timetables right out of the box.

**Comment by brendannee** [comment]
Awesome.

Don't hesitate to open a new issue if you find something else that would make this library work better with the variety of GTFS files out there.

Are you working to implement schedules for a specific transit agency? If so, do a pull request on the README and add the agency to the list of agencies using this library.
