### ISSUE TITLE
GTFS attempting to delete my downloads folder

### ISSUE THREAD

**Issue by lonniusmax** [BlinkTagInc/gtfs-to-html#44]
I'm walking through this for the first time, and I finally think I got everything installed correctly. However, when I run gtfs-to-html, I get an error "Error: EACCES: permission denied, rmdir '/Users/{myusername}/downloads'. I'm running on MacOS X 10.11.6. Due to the nature of the folder, I definitely do NOT want to give it the ability to do this (as this is where all Downloads from Safari go. I originally thought it was due to setting a url to our data. However, after switching to a local path in config.json, I'm still receiving the error.

**Comment by brendannee** [comment]
Try running it from somewhere other than /Users/{myusername} - it creates a folder called "downloads" for downloading GTFS and then tries to remove it when finished.

**Comment by brendannee** [comment]
I just pushed an update which uses a different folder instead of one named "downloads" so this issue shouldn't happen again.

**Comment by lonniusmax** [comment]
That makes sense. However, I've tried moving even to root and it still gives me the same error. Any suggestions on how to change the folder where it's trying to write the files?

**Comment by lonniusmax** [comment]
Great, brendannee. Thanks. I'll try again.
