### ISSUE TITLE
No trips found for route_id

### ISSUE THREAD

**Issue by lonniusmax** [BlinkTagInc/gtfs-to-html#46]
Seemed to be working fine until the latest batch of GTFS data. Now I'm getting "no trips found" error. I tried removing the offending route from routes.txt, but the next one then throws the error.

Starting GTFS import for 1 file
[agency]: Importing GTFS from /Users/[username]/GTFStoHTML/node_modules/gtfs-to-html/google_transit.zip
[agency]: Importing - agency.txt - 1 lines imported
[agency]: Importing - calendar_dates.txt - 17 lines imported
[agency]: Importing - calendar.txt - 10 lines imported
[agency]: Importing - fare_attributes.txt - 2 lines imported
[agency]: Importing - fare_rules.txt - 127 lines imported
[agency]: Importing - feed_info.txt - No file found
[agency]: Importing - frequencies.txt - No file found
[agency]: Importing - routes.txt - 124 lines imported
[agency]: Importing - shapes.txt - 277274 lines imported
[agency]: Importing - stop_times.txt - 415019 lines imported
[agency]: Importing - stops.txt - 2874 lines imported
[agency]: Importing - transfers.txt - No file found
[agency]: Importing - trips.txt - 2339 lines imported
[agency]: Post Processing data
[agency]: Completed GTFS import
Completed GTFS import for 1 file
Error: No trips found for route_id=8857, direction_id=0, service_ids=["3_merged_1023652"], timetable_id=8857_1111100_0
    at getTripsFromTimetable (/Users/[username]/GTFStoHTML/node_modules/gtfs-to-html/lib/utils.js:365:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by brendannee** [comment]
Can you link to the GTFS file you are using?

One option is to add a timetables.txt https://github.com/BlinkTagInc/gtfs-to-html#build-timetablestxt file to your GTFS. This is a non-standard file that tells GTFS-to-HTML which routes and directions you'd like it to build schedules for - so it will ignore all other routes in your GTFS which you don't explicitly specify.

**Comment by lonniusmax** [comment]
Sure. Here's the feed: [http://transitfeeds.com/p/sun-metro/620/latest](url). I've also attached it.
[google_transit.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/1657913/google_transit.zip)

**Comment by brendannee** [comment]
I just pushed an updated version 0.13.4 - this should solve this issue and generate timetables for each route.

Note that for merged GTFS files like this, if you want to be able to specify a set of dates, you'll need to use a timetables.txt file. Without it, all trips for a specific route across all dates will be shown.

**Comment by brendannee** [comment]
Closing this issue - please comment if it is still not working as expected.
