### ISSUE TITLE
Crash during schedule generation

### ISSUE THREAD

**Issue by vanwarantion** [BlinkTagInc/gtfs-to-html#49]
An exception is causing gtfs-to-html to crash with the following output:
`Error: No trips found for route_id=12345, direction_id=0, service_ids=["14","10","8","17","13","7","4"], timetable_id=2452_34_0000010_0
    at getTripsFromTimetable (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:413:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

Process should skip the route if result of `gtfs.getTrips(tripQuery) ` is empty.

**Comment by brendannee** [comment]
I made the code throw an error when no trips are found to force keeping an updated timetables.txt file - you should remove this line from your timetables.txt file.

Perhaps there should be an option in config.json to ignore timetables with no trips?

**Comment by vanwarantion** [comment]
I had to remove around 20 lines from a GTFS file I had received, every time re-running it and waiting to crash.. I think config option is a great idea. Also perhaps the default behaviour should be to throw a warning instead. This is a great tool otherwise.

**Comment by brendannee** [comment]
This is a great idea.

Check out the latest release https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.13.12 - many things that were errors are now warnings, which should really help out in your case.

Try it out and let me know what you think.
