### ISSUE TITLE
No file found?

### ISSUE THREAD

**Issue by jimijack** [BlinkTagInc/gtfs-to-html#50]
I'm testing locally for a transit feed I've run `gtfs-to-html` successfully in the past, however I was using a URL. This time I'm just running it from a `.zip` folder on my computer. I know I have the path correct but it keeps saying "No file found" for any of the `.txt` files in the `feed.zip` folder. They are all there.

`$ gtfs-to-html`

`Starting GTFS import for 1 file`
`testAgency: Importing GTFS from ~/Downloads/feed.zip`
`testAgency: Importing - agency.txt - No file found`
`testAgency: Importing - calendar_dates.txt - No file found`
`testAgency: Importing - calendar.txt - No file found`
`testAgency: Importing - fare_attributes.txt - No file found`
`testAgency: Importing - fare_rules.txt - No file found`
`testAgency: Importing - feed_info.txt - No file found`
`testAgency: Importing - frequencies.txt - No file found`
`testAgency: Importing - routes.txt - No file found`
`testAgency: Importing - shapes.txt - No file found`
`testAgency: Importing - stop_times.txt - No file found`
`testAgency: Importing - stops.txt - No file found`
`testAgency: Importing - transfers.txt - No file found`
`testAgency: Importing - trips.txt - No file found`
`testAgency: Post Processing data`
`testAgency: Completed GTFS import`
`Completed GTFS import for 1 file`
`Error: No agency found for agency_key=testAgency`
`   at Object.exports.generateOverviewHTML (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:769:11)`
`    at <anonymous>`
`    at process._tickCallback (internal/process/next_tick.js:188:7)`

I'm trying to add the `timetables.txt` file for the first time. Hasn't worked yet. Any help appreciated.

**Comment by brendannee** [comment]
Make sure that the zip file does not contain folders or subfolders - the .txt files should be directly inside the zipfile.

Let me know if that solves it.

**Comment by jimijack** [comment]
Hey Brendan thanks for getting back so quick.
Yup, I had re-zipped the containing folder, not zipped all the .txt files together.
All's good. Thanks!

**Comment by brendannee** [comment]
I just pushed an update version 1.6.3 that will give a more helpful error message when your zipfile contains subfolders. I have dealt with this issue before.
