### ISSUE TITLE
No trips found?

### ISSUE THREAD

**Issue by jimijack** [BlinkTagInc/gtfs-to-html#51]
I need help understanding this error I'm getting because the route_id in question has trips associated with it. There's only one service_id associated with the route in question (7501) so I'm confused why these other service_ids are showing:

`$ gtfs-to-html`

`Starting GTFS import for 1 file`
`testAgency: Importing GTFS from ./test-feed.zip`
`testAgency: Importing - agency.txt - 1 lines imported`
`testAgency: Importing - calendar_dates.txt - 469 lines imported`
`testAgency: Importing - calendar.txt - 53 lines imported`
`testAgency: Importing - fare_attributes.txt - No file found`
`testAgency: Importing - fare_rules.txt - No file found`
`testAgency: Importing - feed_info.txt - 1 lines imported`
`testAgency: Importing - frequencies.txt - No file found`
`testAgency: Importing - routes.txt - 45 lines imported`
`testAgency: Importing - shapes.txt - 37007 lines imported`
`testAgency: Importing - stop_times.txt - 88887 lines imported`
`testAgency: Importing - stops.txt - 696 lines imported`
`testAgency: Importing - transfers.txt - No file found`
`testAgency: Importing - trips.txt - 4170 lines imported`
`testAgency: Importing - timetables.txt - 125 lines imported`
`testAgency: Importing - timetable_stop_order.txt - 609 lines imported`
`testAgency: Post Processing data`
`testAgency: Completed GTFS import`
`Completed GTFS import for 1 file`
`testAgency: Generating 56 of 125 HTML schedules`
`Warning: No trips found for route_id=5222, direction_id=1, service_ids=["1","29510","3810","43310","29803","29503","30303","43303","29502","29602","43202","29501","17601","27201","3701","48001","43001","43101","37001","34301","1101","24701","30701","25201","10"], timetable_id=161`
`TypeError: Cannot read property 'stoptimes' of undefined`
`    at findCommonStopId (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:33:45)`
`    at sortTrips (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:96:24)`
`    at getTripsFromTimetable (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:539:10)`
`    at <anonymous>`
`    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by brendannee** [comment]
Can you link the GTFS file you are working on?

**Comment by brendannee** [comment]
In your timetables.txt, you may be specifying a date range for which that route has no service. Or, perhaps it doesn't have any service in direction_id=1.

GTFS-to-HTML queries for all service_ids for the date range specified in timetables.txt, and 7501 doesn't appear to be one of those.

**Comment by jimijack** [comment]
Hey Brendan thanks for getting back so quick again. Apologies there's a learning curve for me. It was the service dates, no service on that route effective yesterday! I just ran again and all populated just fine.

Thanks again for the quick note back. Can close this one out!

j
