### ISSUE TITLE
Filtered timetable_stop_order not correct

### ISSUE THREAD

**Issue by jimijack** [BlinkTagInc/gtfs-to-html#52]
I'm struggling to understand where this break might be happening because Im not sure where to look anymore. The timetables for one particular route in which I am filtering out some specific time points is not matching up, generating a timetable with '---' in place of the time that should be there.

I've cross-checked it numerous times making sure the stop_id matches, and it does, but when I run the command the new timetables do not include the stop_id points I'm declaring.

I've attached an image showing part of the unfiltered timetable, direct from the normal gtfs feed, and part of the new filtered timetable. You'll see the stop codes match under the location names.

I'm just not sure where to look to get a better understanding. Any help appreciated.  I can also attached the feed if necessary. Thanks!

James

![gtfs-to-html-result](https://user-images.githubusercontent.com/14816657/40738693-1bed0884-63f9-11e8-910f-c1a339066c3e.jpg)

**Comment by brendannee** [comment]
Can you link me the to GTFS you are using and any others steps needed to recreate this issue?

**Comment by jimijack** [comment]
Hey I apologize for not getting back with you on this one I admit I didn't realize it was still an open ticket. This issue has been resolved. That being said I was going to open a new request with a different question regarding duplicate times, which will have the file structure in a repo for you.
