### ISSUE TITLE
Timetables shouldn't include exception calendar trips

### ISSUE THREAD

**Issue by hkvlhm** [BlinkTagInc/gtfs-to-html#53]
Exception service (added service in calendar_dates.txt) is showing up in timetables, but it should be excluded.

Example: 

SCT's Route 24 operates its Saturday service instead of Mon-Fri service on New Year's Eve. calendar_dates.txt shows:

service_id,date,holiday_name,exception_type
c_15300_b_none_d_32,20181231,New Years Eve,1

The trips associated with that exception calendar are included in Route 24's Mon-Fri timetable. In our GTFS these are easily identifiable because they have "none" in the trip_id (e.g. t_294330_b_none_tn_0).

Route 24's relevant timetables and SCT's GTFS:
[sct_r24.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/2055118/sct_r24.zip)
[sonomacounty-ca-us.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/2055084/sonomacounty-ca-us.zip)

**Comment by brendannee** [comment]
Try adding an `exclude_exceptions` column to `timetables.txt` and set the value to `1` for each timetable (see attached)
[timetables.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/2056062/timetables.txt)

This field will exclude holiday service that happens weekdays.

@thomastrillium @antrim Do you think that the default value for `exclude_exceptions` should be `1`?

**Comment by brendannee** [comment]
I agree with your gut reaction.

I pushed a new release 0.13.15 which changed the field to `include_exceptions` with a default of 0 (so most `timetables.txt` probably won't need to include this field.

Not building SCT's GTFS should yield the desired results.
