### ISSUE TITLE
Duplicate times, multiple timetables

### ISSUE THREAD

**Issue by jimijack** [BlinkTagInc/gtfs-to-html#54]
I have an issue where the trips for a Sunday timetable are being generated on a Weekday timetable. I'm not sure where the distinguishing element would be to change. Obviously we can't delete the trip_id because the times are correct for the Sunday timetable.

How do I delete these extra trips from the Weekday timetable while still keeping them on the Sunday timetable? Is there another .txt file I should be using to make sure trip_ids are specific for applicable timetable_ids?

For this specific example, there is a route_id associated with Route 20.

On the timetables.txt file:
```
200,5224,0,20180611,20180819,1,1,1,1,1,0,0,0,Route 20 Weekday toward Carpinteria,Mon-Fri,vertical,200,0,Carpinteria
201,5224,1,20180611,20180819,1,1,1,1,1,0,0,0,Route 20 Weekday toward Downtown,Mon-Fri,vertical,201,0,Downtown
202,5224,0,20180611,20180819,0,0,0,0,0,1,0,0,Route 20 Saturday toward Carpinteria,Saturday,vertical,202,0,Carpinteria
203,5224,1,20180611,20180819,0,0,0,0,0,1,0,0,Route 20 Saturday toward Downtown,Saturday,vertical,203,0,Downtown
204,5224,0,20180611,20180819,0,0,0,0,0,0,1,0,Route 20 Sunday toward Carpinteria,Sunday,vertical,204,0,Carpinteria
205,5224,1,20180611,20180819,0,0,0,0,0,0,1,0,Route 20 Sunday toward Downtown,Sunday,vertical,205,0,Downtown
```
The schedule for Weekday, Saturday towards Carpinteria also contain **Sunday’s** times: 
	- the trip beginning at 6:45am (`trip_id_620430`) shouldn't be on Weekday, but correct for Sunday;
	- the first of two trips beginning at 7:45am (`trip_id_620431`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 8:30am (`trip_id_620432`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 9:30am (`trip_id_620433`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 10:45am (`trip_id_620434`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 11:45am (`trip_id_620435`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 12:45pm (`trip_id_620436`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 1:45pm (`trip_id_620437`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 2:45pm (`trip_id_620438`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 3:45pm (`trip_id_620439`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 5:45pm (`trip_id_620441`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 6:45pm (`trip_id_620442`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 8:00pm (`trip_id_620443`) shouldn't be on Weekday, but correct for Sunday;
	- the trip beginning at 10:50pm (`trip_id_620803`) shouldn't be on Weekday, but correct for Sunday;

You can access the repo files [here](https://github.com/jimijack/timetables_sbmtd).

Really appreciate the help!

j

**Comment by brendannee** [comment]
Can you link to the GTFS file you are using and your timetables.txt file - I'll check it out.

**Comment by jimijack** [comment]
Sure I'm running it all locally (downloaded feed from server.) The repo is [timetables_sbmtd](https://github.com/jimijack/timetables_sbmtd) **which has all the applicable files**. If you need the feed directly from from the server though its [here](http://sbmtd.gov/google_transit/feed.zip).

**Comment by jimijack** [comment]
Hey Brendan I think I found the issue, though you might need to explain/clarify if this is something you see often. I'll try not to make your head spin.

The problem is in the `service_id`. The `calendar.txt` file contains binary values for applicable days for `service_id` `1`, `2`, and `3`, and all days are zeroed out for the rest of the `service_id`s on the `calendar.txt` file.

When I dig into the `trips.txt`, I found a lot of `trip_id`s connected to the route that had a `service_id` of `10`, which doesn't have any designated binary values for days of the week on `calendar.txt`. 
Once I changed those `service_id`s that were `10` to a `service_id` of `3` for Sunday, they were removed from the Weekday schedule. Same for the Saturday duplicate.

I think what this means is the client is going to have to update their feed they send to Google with accurate `service_id`s for the `route_id`s. Unless you know of a quicker solution?

Thanks again for taking a look.

j

**Comment by brendannee** [comment]
When I ran GTFS-to-HTML against that GTFS feed with this [timetables.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/2172322/timetables.txt), I got the following: https://sbmtd-bvrfrmfxrg.now.sh/

On first glance, it looks like the timetables it generated don't have the issues you outlined.

Are you using the most up-to-date version of gtfs-to-html 0.14.1? I think the issue you are seeing was resolved in a release a few weeks ago.

**Comment by jimijack** [comment]
Hey good morning Brendan thanks for getting back with me. Yes looks like the updated version resolved the issue with the duplicate times. Got some extra knowledge troubleshooting which is never a bad thing! 
I am however now getting timetable generation errors for a couple routes, one of which is `route_id=5243` for shuttle line 27. These were populating before.

```
Warning: No trips found for route_id=5243, direction_id=1, service_ids=["1"], timetable_id=277
test-0709: Generating 15 of 119 HTML schedules
Warning: No trips found for route_id=5243, direction_id=0, service_ids=["1"], timetable_id=276
test-0709: Generating 20 of 119 HTML schedules
Warning: No trips found for route_id=5243, direction_id=1, service_ids=["1"], timetable_id=271
test-0709: Generating 21 of 119 HTML schedules```
Warning: No trips found for route_id=5243, direction_id=0, service_ids=["1"], timetable_id=270
test-0709: Generating 52 of 119 HTML schedules
```

**Comment by brendannee** [comment]
Set `include_exceptions` to 1 for the timetables where you'd like to include those service ids. https://github.com/BlinkTagInc/gtfs-to-html#build-timetablestxt

I tried this out with your feed and it did work to generate timetables for that route for M-F.  Try it out and let me know if that works for you.

**Comment by jimijack** [comment]
Ok got times to generate, but its listing both the weekday AND alternate schedule times together n both, rather than separate. If I add a 0 value for `include_exceptions` on the weekday schedule no times generate. Can I add an `exclude_exceptions` value to differentiate the two? That used to be one of the fields.

**Comment by brendannee** [comment]
This is tricky - there is not currently a way to exclude some exceptions and not others. Perhaps I need to add a column to timetables.txt that lets you specify exact service_ids to include.

In the mean time, there are a few ways to solve this:

* If the alternate schedules only happen on one specific day of the week (for example, Wednesday for 4th of july this year) generate a timetable for only Monday which will not include the alternative schedules - you can title this timetable M-F.

* Add a custom template and manually filter out unwanted trips at the template level https://github.com/BlinkTagInc/gtfs-to-html/blob/master/views/timetable/timetable_vertical.pug#L23

* Each row in a timetable gets a unique id based on its trip_id - you could use css to hide these (be aware this can affect accessibility)

Let me know if any of these solutions work for you. I think the best answer is for the agency to not use exceptions in calendar_dates.txt for their normal M-F schedules.

**Comment by jimijack** [comment]
Ok tried the CSS update approach. I figure its the quickest solution for now. At least its just a couple shuttle lines I have to prep for.

The alternate schedule happens during the week while school is out, so I'll try and add another timetable using the M-F suggestion.

Really appreciate you keeping up with me on this one.  Thanks again for the help. I agree their .txt files could be organized a little better. I'll prob wind up creating new timetables by adding to the trips.txt and getting rid of the exceptions that last all week.

**Comment by brendannee** [comment]
Great, glad it worked.

Is this going to be used on the agency's website?

**Comment by jimijack** [comment]
Potentially pending review of the process and output. I'll let you know as soon as they confirm. I'm almost positive they will.

**Comment by brendannee** [comment]
It looks like SBMTA is using GTFS-to-HTML now - so I added it to the list of agencies using GTFS-to-HTML in the readme.
