### ISSUE TITLE
getting error: Error: Unable to initialize Mongo bulk insert

### ISSUE THREAD

**Issue by BenPav** [BlinkTagInc/gtfs-to-html#55]
On OSX, trying to run on commandline, I get this error

**Comment by BenPav** [comment]
Nevermind, mongo wasn't properly loaded in my environment

**Comment by brendannee** [comment]
Glad you got this figured out.

**Comment by Behodar** [comment]
Can anyone advise how to "properly load" Mongo? I'm getting the same error, and having never used MongoDB in my life I'm a bit lost. If I run Compass then it happily connects to localhost:27017 and shows me three default databases, but gtfs-to-html just fails with the "unable to initialise" message (with mongodb://localhost:27017/gtfs in config.json).

I'm running Windows 7, Node 10.13 and MongoDB 4.0.3 (installed as a service).

Any assistance would be appreciated :)

**Comment by Pawajoro** [comment]
Let me "refresh" that issue as I face similar problem, but in a bit strange way.

When I try to build one of my GTFSes (config attached as .txt as Git doesn't like .json: [config-KW.json.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/2783730/config-KW.json.txt)) everything looks fine:
![obraz](https://user-images.githubusercontent.com/46163160/51550590-f3f91780-1e6c-11e9-9e31-6f108435f654.png)
Mongo responds too (whole log is longer, but here is irrelevant):
![obraz](https://user-images.githubusercontent.com/46163160/51550688-2b67c400-1e6d-11e9-8aaa-95ab2ba6db12.png)

I also tried to put that **unmodified** GTFS on my local Apache server and in config I linked to it via loopback (config in .txt: [config-KW2.json.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/2783755/config-KW2.json.txt)), but:
![obraz](https://user-images.githubusercontent.com/46163160/51551303-7afabf80-1e6e-11e9-9aea-6bc15f81ea97.png)
Nothing occurs in Mongo cmd (there is no information about this try there)

I gave a try to `npm start`, as you suggested before, and all looks fine (tried also to call it via browser on :3000): 
![obraz](https://user-images.githubusercontent.com/46163160/51549039-e0987d00-1e69-11e9-9e8e-5d8f7edc9908.png)
Also MongoDB responds to that try:
![obraz](https://user-images.githubusercontent.com/46163160/51549146-1f2e3780-1e6a-11e9-943e-24df268a9069.png)

I have no idea what is wrong. gtfs-to-html actually **can** connect with Mongo, but it is imposible with some GTFS adresses (with both tries zips was identical). I'm sorry in advance, if I've done some mistake - new in node.js

I'm waiting for hearing from you. Should I send GTFS concerned?

**Comment by Behodar** [comment]
Sorry! I'd completely forgotten about this. We ended up getting a third-party supplier to sort things out at my end, so I'm not sure what the fix was for my particular issue. Hopefully someone else can help you out :)

**Comment by brendannee** [comment]
Can you try upgrading the version of mongo on your system to version 4.x? That may help solve the issue as it looks like you are running a 3.x version.

**Comment by Pawajoro** [comment]
> 
> 
> Can you try upgrading the version of mongo on your system to version 4.x? That may help solve the issue as it looks like you are running a 3.x version.

I had already 4.0.5 when tried

**Comment by brendannee** [comment]
In the screenshots posted above I see "mongodb-core: 3.1.9" - can you run the command `mongod` and see what version it outputs when you run that?

Also, you can try removing your `node_modules` folder and re-running npm install - see if that helps solve this.

**Comment by Pawajoro** [comment]
I'm really thankful for your help. But the answer is... a bit stupid.

I had to use 127.0.0.1:27017 instead of localhost:27017. 

I write it here, if some more fools like me got into trouble :)

**Comment by brendannee** [comment]
Interesting - is that a windows specific issue? How did you track it down?
Do you think we should update the default mongoURL here to use 127.0.0.1?
https://github.com/BlinkTagInc/gtfs-to-html/blob/master/config-sample.json#L2
