### ISSUE TITLE
Possible to make Google Maps Version?

### ISSUE THREAD

**Issue by BenPav** [BlinkTagInc/gtfs-to-html#56]
I'm working on a project with multiple parts already using the Google Maps API, and to have a version of this that's Google Maps-friendly would be very helpful.

**Comment by brendannee** [comment]
It is definitely possible - all of the mapping code is here: https://github.com/BlinkTagInc/gtfs-to-html/blob/master/public/js/timetable-map.js - so you could make a custom template for GTFS-to-HTML that includes a different javascript file with google maps code.
