### ISSUE TITLE
node: No such file or directory

### ISSUE THREAD

**Issue by CharlesBelov** [BlinkTagInc/gtfs-to-html#57]
I'm trying to run gtfs-to-html for the first time. I've installed mongodb, npm, and gtfs-to-html.

When I attempt to run gtfs-to-html, I get the error:
/usr/bin/env: ‘node’: No such file or directory

mongodb is running.

/usr/local/lib/node_modules/gtfs-to-html/ contains a file config.json which contains:

{
  "mongoUrl": "mongodb://localhost:27017/gtfs",
  "agencies": [
    {
      "agency_key": "sfmta",
      "url": "https://gtfs.sfmta.com/transitdata/google_transit.zip"
    }
  ],
  "beautify": false,
  "coordinatePrecision": 5,
  "effectiveDate": "July 8, 2016",
  "interpolatedStopSymbol": "•",
  "linkStopUrls": true,
  "mapboxAccessToken": "YOUR MAPBOX ACCESS TOKEN'",
  "menuType": "simple",
  "noServiceSymbol": "—",
  "requestPickupSymbol": "***",
  "noPickupSymbol": "**",
  "requestDropoffSymbol": "†",
  "noDropoffSymbol": "‡",
  "showMap": true,
  "showOnlyTimepoint": true,
  "showRouteTitle": true,
  "showStopCity": false,
  "zipOutput": false
}

Please assist, thank you.

**Comment by brendannee** [comment]
It sounds like node is not available in your path.

https://stackoverflow.com/questions/30281057/node-forever-usr-bin-env-node-no-such-file-or-directory

Try `node -v` to see whether you've installed node.

**Comment by CharlesBelov** [comment]
That was it, thank you. I've now installed node. 

Alas, running gtfs-to-html now gets:

/usr/local/lib/node_modules/gtfs-to-html/bin/gtfs-to-html.js:39
const getConfig = async () => {
                        ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

This happens whether or not I specify the path to the config.json file.

**Comment by brendannee** [comment]
I think you are running and old version of node - get node version 8 at least, preferably 10.

Try `node -v` to see what version of node.js you have installed.

**Comment by CharlesBelov** [comment]
That was it. Was on 4.2.6., now on 11.6.0. On to mundane issues like my config file isn't in the right place. Thank you for your help!

**Comment by brendannee** [comment]
Adding details and clarifications to the readme would be great, so if you
see something that could be clarified please make a pull request or just
let me know your suggestion and I’ll add it.
