### ISSUE TITLE
Print timetable

### ISSUE THREAD

**Issue by ghido** [BlinkTagInc/gtfs-to-html#58]
Hi, did you plan the possibility to create a pdf from gtfs-to-html?

Thank you fro your job

Ghido

**Comment by brendannee** [comment]
That could definitely be a possibility - the HTML out put clould be rendered to pdf using something like this: https://www.npmjs.com/package/html-pdf

**Comment by brendannee** [comment]
I'll leave this issue open to see if other users would have a use for PDF timetables.

**Comment by joriscode** [comment]
Hi! I'm in favor of this idea!

**Comment by brendannee** [comment]
@joriscode @ghido Which transit agencies are you working with? Do you have some example existing PDFs for schedules that I could work with to try to reproduce?

**Comment by ghido** [comment]
Hi, i working on SIA Brescia (Italy) and i attached one of our PDF.
[LN007.pdf](https://github.com/BlinkTagInc/gtfs-to-html/files/3512101/LN007.pdf)

Thank you

**Comment by brendannee** [comment]
I got a working version of PDF export added to the latest version of GTFS-to-HTML 0.18.0.

Add the option "outputFormat": "pdf" to the config.json file and PDFs will be generated.

You can completely customize the HTML used to format the output by copying the `views/timetable` folder to `views/custom/my-agency` and adding "templatePath": "views/custom/my-agency/" to the confg.json.

(be sure to run `npm install` after getting the latest version of GTFS-to-HTML first).

Try it out and let me know your feedback.
