### ISSUE TITLE
stop_desc as optional field, default off

### ISSUE THREAD

**Issue by evantrillium** [BlinkTagInc/gtfs-to-html#60]
cc: @thomastrillium 

Could we have the stop_desc field made into a field that can be turned on/off in the json, and have the default be off? Right now, some agencies have a great deal of text included in this field, and it creates extremely cumbersome timetables that require manual editing to remove the added field values.

**Comment by evantrillium** [comment]
Here is an example of the json and output for some timetables on https://nworegontransit.org

JSON
https://drive.google.com/file/d/18avF4Jl1htxTTgve2CnQMpQG_bK4rp_a/view?usp=sharing

HTML output
https://drive.google.com/file/d/1DAUOHk3trE7ihlnsRFwkhqXOWUIuIfLT/view?usp=sharing
https://drive.google.com/file/d/1vjubRM-ahHMujkki1K2SZCk0H_r-U1ED/view?usp=sharing

GTFS
http://data.trilliumtransit.com/gtfs/nwconnector-or-us/nwconnector-or-us-timetables.zip

**Comment by brendannee** [comment]
I added an option to config.json which will control showing stop descriptions, with a default of false:

https://github.com/BlinkTagInc/gtfs-to-html#showstopdescription

Is it ok to control this on a per-agency basis, or do you think some agencies would need it on a per-timetable basis?

If this looks like it works, I'll publish an updated version to NPM.

**Comment by evantrillium** [comment]
@brendannee - I don't believe this would need to be per-timetable; I believe at this time, per agency should be sufficient.

Thank you!

**Comment by brendannee** [comment]
Great. Let me know what you think of the latest commit. If it meets your needs, I'll ship an updated version.

Note that it will actually be per-GTFS file, not per-agency (all agencies within the same GTFS file get the same global config). If you did have the scenario where you wanted some timetables with description and some without, you could just run the script twice with two different config files and then pick out the timetables from each set.

**Comment by evantrillium** [comment]
confirmed successful timetable generation without stop_desc. Per-GTFS file is fine (we have the capacity to include/exclude any number of agencies/routes in a GTFS data set).

Thank you for doing this!

**Comment by brendannee** [comment]
OK - version 0.15.0 now has this config option: https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.15.0
