### ISSUE TITLE
Turn off service parameters (dropoff, pickup)?

### ISSUE THREAD

**Issue by evantrillium** [BlinkTagInc/gtfs-to-html#61]
Is it possible to turn off some of the new service parameters that have been added, like  
  "noPickupSymbol": "**",
  "requestDropoffSymbol": "†",
  "noDropoffSymbol": "‡",

Most of the timetables I generate just use a generic "R" for all of these, so having additional qualifiers is unnecessary. Would like to be able to suppress these from generating.

**Comment by brendannee** [comment]
Great idea.

I pushed version 0.16.1 that supports using `null` as a value for any of these symbols and if used it will suppress them from the output. Check it out and let me know what you think.
