### ISSUE TITLE
Error: MongoError: cursor id 138034507560 not found

### ISSUE THREAD

**Issue by kersianuy** [BlinkTagInc/gtfs-to-html#62]
Hello Im having trouble when I run gtfs-to-html command, I have MongoDB running

this is the error while already generating HTML code: 
Error: MongoError: cursor id 138034507560 not found
{ MongoError: cursor id 138034507560 not found
    at C:\Program Files\nodejs\node_modules\gtfs-to-html\node_modules\mongodb-co
re\lib\connection\pool.js:581:63
    at authenticateStragglers (C:\Program Files\nodejs\node_modules\gtfs-to-html
\node_modules\mongodb-core\lib\connection\pool.js:504:16)
    at Connection.messageHandler (C:\Program Files\nodejs\node_modules\gtfs-to-h
tml\node_modules\mongodb-core\lib\connection\pool.js:540:5)
    at emitMessageHandler (C:\Program Files\nodejs\node_modules\gtfs-to-html\nod
e_modules\mongodb-core\lib\connection\connection.js:310:10)
    at Socket.<anonymous> (C:\Program Files\nodejs\node_modules\gtfs-to-html\nod
e_modules\mongodb-core\lib\connection\connection.js:489:15)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
  ok: 0,
  errmsg: 'cursor id 138034507560 not found',
  code: 43,
  codeName: 'CursorNotFound',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: { isGetMore: true } }

npm -v = 6.7.0
node -v = v11.13.0

I really want to this work its a really good program!

Best regards.

**Comment by kersianuy** [comment]
npm start brings this:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Compu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.7.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gtfs-to-html@0.16.2~prestart: gtfs-to-html@0.16.2
6 info lifecycle gtfs-to-html@0.16.2~start: gtfs-to-html@0.16.2
7 verbose lifecycle gtfs-to-html@0.16.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle gtfs-to-html@0.16.2~start: PATH: C:\Users\Compu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Compu\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\.bin;C:\Users\Compu\AppData\Roaming\npm\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Live\Shared;C:\Android;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files\nodejs\;C:\Users\Compu\AppData\Roaming\npm
9 verbose lifecycle gtfs-to-html@0.16.2~start: CWD: C:\Users\Compu\AppData\Roaming\npm\node_modules\gtfs-to-html
10 silly lifecycle gtfs-to-html@0.16.2~start: Args: [ '/d /s /c', 'node ./app' ]
11 silly lifecycle gtfs-to-html@0.16.2~start: Returned: code: 1  signal: null
12 info lifecycle gtfs-to-html@0.16.2~start: Failed to exec start script
13 verbose stack Error: gtfs-to-html@0.16.2 start: `node ./app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Compu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Compu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid gtfs-to-html@0.16.2
15 verbose cwd C:\Users\Compu\AppData\Roaming\npm\node_modules\gtfs-to-html
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Compu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v11.13.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error gtfs-to-html@0.16.2 start: `node ./app`
22 error Exit status 1
23 error Failed at the gtfs-to-html@0.16.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kersianuy** [comment]
npm start command bring this:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Compu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.7.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gtfs-to-html@0.16.2~prestart: gtfs-to-html@0.16.2
6 info lifecycle gtfs-to-html@0.16.2~start: gtfs-to-html@0.16.2
7 verbose lifecycle gtfs-to-html@0.16.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle gtfs-to-html@0.16.2~start: PATH: C:\Users\Compu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Compu\AppData\Roaming\npm\node_modules\gtfs-to-html\node_modules\.bin;C:\Users\Compu\AppData\Roaming\npm\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Live\Shared;C:\Android;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files\nodejs\;C:\Users\Compu\AppData\Roaming\npm
9 verbose lifecycle gtfs-to-html@0.16.2~start: CWD: C:\Users\Compu\AppData\Roaming\npm\node_modules\gtfs-to-html
10 silly lifecycle gtfs-to-html@0.16.2~start: Args: [ '/d /s /c', 'node ./app' ]
11 silly lifecycle gtfs-to-html@0.16.2~start: Returned: code: 1  signal: null
12 info lifecycle gtfs-to-html@0.16.2~start: Failed to exec start script
13 verbose stack Error: gtfs-to-html@0.16.2 start: `node ./app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Compu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Compu\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid gtfs-to-html@0.16.2
15 verbose cwd C:\Users\Compu\AppData\Roaming\npm\node_modules\gtfs-to-html
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Compu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v11.13.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error gtfs-to-html@0.16.2 start: `node ./app`
22 error Exit status 1
23 error Failed at the gtfs-to-html@0.16.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kersianuy** [comment]
I see that always happend within 10 minutes of generating the HTML code, could it be cursor timeout related?

**Comment by brendannee** [comment]
Do you mean it happens after 10 minutes of running the gtfs-to-html command? Which agency are you running this for - can you link me to their GTFS?

**Comment by Pawajoro** [comment]
You must not use Windows Notepad. I had that problem, when used it. Use
Notepad++ for example :)

Best regards,
Orest



niydz., 7.04.2019, 23:48 użytkownik kersianuy <notifications@github.com>
napisał:

**Comment by kersianuy** [comment]
@brendannee
t's for an Uruguayan company called Cutcsa, we are in the process of changing our system to GTFS and testing of could we show our shedules. This is the link: http://www.cutcsa.com.uy/content/uploads/2019/04/gtfs.zip

@Pawajoro
I used notepad ++ but could be a codification issue? I saved all the files In ANSI , i don't know if they have to be in UTF?


Thanks for the quick response!!!
Best regards

**Comment by brendannee** [comment]
Wow - that would be exciting to have this library used for generating schedules for such a large agency.

I found the issue and updated the node-gtfs library and gtfs-to-html to avoid this timeout issue. https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/0.16.3

Download the latest version and see if it works for you.

**Comment by kersianuy** [comment]
Now it worked!! However Im not seeing a map and the export brings me all the stops and I would like only timepoints, in the config.json I put both of the options and the token from mapbox, this is the code of the config:

{
  "mongoUrl": "mongodb://localhost:27017/cutcsa",
  "agencies": [
    {
      "agency_key": "cutcsa",
      "url": "the link I posted/gtfs.zip"  } ]
,
      "exclude": [
        "shapes"
      ]
, "beautify": true,
  "coordinatePrecision": 5,
  "effectiveDate": "January 1, 2019",
  "menuType": "simple",
  "noServiceSymbol": "—",
  "requestStopSymbol": "***",
  "interpolatedStopSymbol": "•",
  "showMap": true,
  "showOnlyTimepoint": true,
  "showStopCity": false,
  "mapboxAccessToken": "pk.eyJ1Ijoia2Vyc2lhbiIsImEiOiJjanVibzF6em0wZmdxM3luNXV0bXMzdm4yIn0.Y08-b1NgK6Vz3ZlN_PLWCw",
  "zipOutput": false  }


Best regards,

**Comment by brendannee** [comment]
Remove 
    "exclude": [
      "shapes"
    ]

from your config and the shapes.txt will get imported which should enable maps.

I'll look into why all timepoints are showing up for you.

**Comment by kersianuy** [comment]
When I eliminate the "remove shapes" , after 10 or 15 minutes it comes this error:

<--- Last few GCs --->

[7404:0000000C99215DB0]   981051 ms: Mark-sweep 1300.8 (1446.6) -> 1289.5 (1447.
6) MB, 1261.0 / 0.0 ms  (average mu = 0.211, current mu = 0.133) allocation fail
ure scavenge might not succeed
[7404:0000000C99215DB0]   982468 ms: Mark-sweep 1303.0 (1447.6) -> 1291.8 (1448.
1) MB, 1206.6 / 0.0 ms  (average mu = 0.181, current mu = 0.149) allocation fail
ure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00000062E06D0481]
Security context: 0x03864ba9d9d1 <JSObject>
    1: once [000003864BADAB59] [events.js:~293] [pc=00000062E102D375](this=0x010
68d33ed29 <EventEmitter map = 00000203C45B9391>,0x03864bad8851 <String[4]: init>
,0x01068d33ef99 <JSFunction Document.once (sfi = 0000035AE7CD74C1)>)
    2: Document [0000012D6C0F1099] [C:\Program Files\nodejs\node_modules\gtfs-to
-html\node_modules\mongoose\lib\document.js:~57] ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaS
cript heap out of memory

Writing Node.js report to file: report.20190410.201709.7404.0.001.json
Node.js report completed
 1: 00007FF7BCAF937A public: __cdecl v8::internal::GCIdleTimeHandler::GCIdleTime
Handler(void) __ptr64+4618
 2: 00007FF7BCAA87F6 uv_loop_fork+85542
 3: 00007FF7BCAA92BD uv_loop_fork+88301
 4: 00007FF7BCECFD8E void __cdecl v8::internal::FatalProcessOutOfMemory(class v8
::internal::Isolate * __ptr64,char const * __ptr64)+798
 5: 00007FF7BCECFCC7 void __cdecl v8::internal::FatalProcessOutOfMemory(class v8
::internal::Isolate * __ptr64,char const * __ptr64)+599
 6: 00007FF7BCF837A4 public: static bool __cdecl v8::internal::Heap::RootIsImmor
talImmovable(int)+14068
 7: 00007FF7BCF795B2 public: bool __cdecl v8::internal::Heap::CollectGarbage(enu
m v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum
v8::GCCallbackFlags) __ptr64+7234
 8: 00007FF7BCF77DC8 public: bool __cdecl v8::internal::Heap::CollectGarbage(enu
m v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum
v8::GCCallbackFlags) __ptr64+1112
 9: 00007FF7BCF816F7 public: static bool __cdecl v8::internal::Heap::RootIsImmor
talImmovable(int)+5703
10: 00007FF7BCF81776 public: static bool __cdecl v8::internal::Heap::RootIsImmor
talImmovable(int)+5830
11: 00007FF7BD0B9641 public: class v8::internal::Handle<class v8::internal::Heap
Object> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::interna
l::AllocationSpace) __ptr64+49
12: 00007FF7BD173506 public: static int __cdecl v8::internal::StoreBuffer::Store
BufferOverflow(class v8::internal::Isolate * __ptr64)+27190
13: 00000062E06D0481

I already tried your command for "big files"

**Comment by brendannee** [comment]
Yikes - the import is pretty memory intensive for large GTFS files.

I was able to import it on my macbook pro with 16 GB memory, perhaps if you try something like:

`node --max-old-space-size= 8192 /usr/local/bin/gtfs-to-html` it will work (allocating 8 GB of memory)

**Comment by brendannee** [comment]
It looks like the timetables generated only show timepoints -see this one for example:

[0ad767f_0000001_0_143_0_sun.html.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/3070459/0ad767f_0000001_0_143_0_sun.html.zip)

If you see timetables that are showing all stops (instead of just timepoints) let me know an example of a route where this is happening.

**Comment by kersianuy** [comment]
I'm trying again with the 8GB size, I have 8GB of RAM only. It's about 10 minutes and 47% of RAM used and got the same error. In the previous attempts I saved with map "false" and got success but the final HTML was a list super narrow and the other 70% of the screen was white (I think the map load here?)

**Comment by kersianuy** [comment]
https://imgur.com/8r3hXZA

**Comment by brendannee** [comment]
That is a super long list. That svcreenshot shows the route summary view (a list of timetables generated). Click through to view a specific timetable.

The white space is a spot designated for a map.

I suggest that you try adding a timetables.txt file to your GTFS and reimport. This file should be formatted as documented here. https://github.com/BlinkTagInc/gtfs-to-html#build-timetablestxt

Try it with just a few routes/directions and see if it helps limit the timetables generated. Without this file, GTFS-to-HTML tries to guess all of the different timetables you want generated, but this can end up with a super long list.

If you want to group timetables together on the same page, you can add a timetable_pages.txt file: https://github.com/BlinkTagInc/gtfs-to-html#build-timetable_pagestxt

**Comment by brendannee** [comment]
Closing this issue - feel free to reopen if there is still more to discuss.
