### ISSUE TITLE
No trips found for route_id

### ISSUE THREAD

**Issue by pmmtt** [BlinkTagInc/gtfs-to-html#66]
Good day there,

I am getting the following error and I cannot for the life of me figure out how to fix it.  Was wondering if you could clue me into what I am missing:

Warning: No trips found for route_id=5625, direction_id=1, service_ids=["1"], timetable_id=281

Any advice?

Thanks in advance,
Patrick

**Comment by brendannee** [comment]
Can you link to the GTFS you are using?

If you remove timetable_id 281 from timetables.txt then it should no longer give you this warning.

**Comment by pmmtt** [comment]
Sorry.  Little bit of a noob here.  Ususally hack away at things till I fix them.  Here is the link.

https://github.com/pmmtt/GTFS-Feeds.git

**Comment by brendannee** [comment]
I reviewed your GTFS - Route 27 and 28 weekdays don't actually have any regularly scheduled trips - only trips that happen on exceptions defined in calendar_dates.txt.

Here is PR that fixes that in your GTFS timetables.txt: https://github.com/pmmtt/GTFS-Feeds/pull/1 - it updates the value of `include_exceptions` to `1`.
