### ISSUE TITLE
Request: showStopCity in vertical timetables

### ISSUE THREAD

**Issue by hkvlhm** [BlinkTagInc/gtfs-to-html#67]
Would it be feasible to add the showStopCity feature to vertical timetables?

e.g. https://ridetcat.org/routes/route-10/ where the HTML timetables are intended to match the agency's PDF schedules (vertical, with city names)

**Comment by brendannee** [comment]
I just pushed an update GTFS-to-HTML version 0.17.5 that adds support for this feature in vertical timetables. Let me know how it works out.
