### ISSUE TITLE
Impossible to find stops

### ISSUE THREAD

**Issue by mzzntn** [BlinkTagInc/gtfs-to-html#71]
**System:**
Mac OS

**Problem:**
The program is able to find the right file with the right stops but is not able to show them in the final html

**Log:**
Starting GTFS import for 1 file
S.T.C.: Importing GTFS from /Users/mzzntn/Nextcloud/GTFS/gtfs.zip
S.T.C.: Importing - agency.txt - 1 lines imported
S.T.C.: Importing - calendar_dates.txt - 6 lines imported
S.T.C.: Importing - calendar.txt - 2 lines imported
S.T.C.: Importing - fare_attributes.txt - 4 lines imported
S.T.C.: Importing - fare_rules.txt - No file found
S.T.C.: Importing - feed_info.txt - 1 lines imported
S.T.C.: Importing - frequencies.txt - No file found
S.T.C.: Importing - routes.txt - 6 lines imported
S.T.C.: Importing - shapes.txt - 5214 lines imported
S.T.C.: Importing - stop_times.txt - 2088 lines imported
S.T.C.: Importing - stops.txt - 75 lines imported
S.T.C.: Importing - transfers.txt - No file found
S.T.C.: Importing - trips.txt - 142 lines imported
S.T.C.: Post Processing data
S.T.C.: Completed GTFS import
Completed GTFS import for 1 file
S.T.C.: Generating HTML timetables [=========] 9/9

S.T.C.: HTML timetables created at /Users/mzzntn/html/S.T.C

![Screenshot 2019-08-31 at 12 23 07](https://user-images.githubusercontent.com/37122612/64062699-22508980-cbea-11e9-92f6-d9df76d5878b.png)

S.T.C.: HTML timetable generation required 7 seconds(base) Antonios-MBP:~ mzzntn$

**Comment by mzzntn** [comment]
It seems that the problem occurs only with this gtfs file:
https://mazzarino.gq/index.php/s/Fzr4fZcEzaX64Gb/download

**Comment by mzzntn** [comment]
Now works 
I changed "showOnlyTimepoint": true, to false as my value are all estimated

**Comment by brendannee** [comment]
Glad it got worked out. Is there a way I could update the README to make this easier to figure out?

**Comment by mzzntn** [comment]
I think that the readme is pretty strait-forward, you (and your team) are doing an amazing job.

The only thing i'm trying to figure out, is how to change the **X = No service at this stop or • = Estimated time of arrival** or again other English information of the html file in Italian, this part that we can call *"translation"* is completely missing in the readme, and since i'm not a super expert i do not know where to seek for this type of information.

P.S.
The killing feature in my opinion would be the native possibility to export in pdf, but probably you already know this

**Comment by brendannee** [comment]
Thanks for the suggestion. I just published version 0.17.10 which allows you configure the text used for these english phrases in the config.json - check out the readme and config-sample.json.

**Comment by mzzntn** [comment]
Hi me again ::, 

I tried the new version this is my config:

{
  "mongoUrl": "mongodb://localhost:27017/gtfs",
    "agencies": [
      {
        "agency_key": "S.T.C",
        "url": "https://mazzarino.gq/index.php/s/Fzr4fZcEzaX64Gb/download"
      }
    ],
  "beautify": true,
  "coordinatePrecision": 5,
  "dateFormat": "DD-MM-YYYY",
  "daysShortStrings": ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
  "daysStrings": ["lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato", "domenica"],
  "defaultOrientation": "horizontal",
  "EffectiveDate": "01-09-2019",
  "interpolatedStopSymbol": null,
  "linkStopUrls": false,
  "mapboxAccessToken": "pk.eyJ1IjoibXp6bnRuIiwiYSI6ImNqenpnMGM2ajE0a3MzbG8xMjV6ZjBuYzgifQ.80nc_zq59i5m2crvztv0Yw",
  "menuType": "simple",
  "noDropoffSymbol": "‡",
  "noDropoffText": "No drop off available",
  "noHead": false,
  "noPickupSymbol": "*#*",
  "noPickupText": "No pickup available",
  _**"noServiceSymbol": "Ø",
  "noServiceText": "Fermata non effettuata",**_
  "requestDropoffSymbol": "†",
  "requestDropoffText": " Must request drop off",
  "requestPickupSymbol": "*#*#*",
  "requestPickupText": "Request stop - call for pickup",
  "serviceNotProvidedOnText": "Service not provided on",
  "serviceProvidedOnText": "Service provided on",
  "showArrivalOnDifference": 0.2,
  "showMap": true,
  "showOnlyTimepoint": false,
  "showRouteTitle": true,
  "showStopCity": false,
  "showStopDescription": false,
  "skipImport": false,
  "sortingAlgorithm": "common",
  "timeFormat": "HH:mm",
  "verbose": false,
  "zipOutput": false
}

but it seems that it doesn't have effect on the final result:

http://www.oilways.org/tpl/timetables/arancione_1111110_undefined_4_lun-sab.html
