### ISSUE TITLE
Non regular service days tables

### ISSUE THREAD

**Issue by mzzntn** [BlinkTagInc/gtfs-to-html#72]
Hi, me again :)

With the last version every time i run the program it creates an additional timetable for each direction with "Non regular service days". Is it possible to disable this feature ? It was not present in the previous version and i think it creates misunderstanding.

My config:

{
  "mongoUrl": "mongodb://localhost:27017/gtfs",
    "agencies": [
      {
        "agency_key": "S.T.C",
        "url": "https://mazzarino.gq/index.php/s/Fzr4fZcEzaX64Gb/download"
      }
    ],
  "beautify": true,
  "coordinatePrecision": 5,
  "dateFormat": "DD-MM-YYYY",
  "daysShortStrings": ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
  "daysStrings": ["lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato", "domenica"],
  "defaultOrientation": "horizontal",
  "EffectiveDate": "01-09-2019",
  "interpolatedStopSymbol": null,
  "linkStopUrls": false,
  "mapboxAccessToken": "pk.eyJ1IjoibXp6bnRuIiwiYSI6ImNqenpnMGM2ajE0a3MzbG8xMjV6ZjBuYzgifQ.80nc_zq59i5m2crvztv0Yw",
  "menuType": "simple",
  "noDropoffSymbol": "‡",
  "noDropoffText": "No drop off available",
  "noHead": false,
  "noPickupSymbol": "**",
  "noPickupText": "No pickup available",
  "noServiceSymbol": "Ø",
  "noServiceText": "Fermata non effettuata",
  "requestDropoffSymbol": "†",
  "requestDropoffText": " Must request drop off",
  "requestPickupSymbol": "***",
  "requestPickupText": "Request stop - call for pickup",
  "serviceNotProvidedOnText": "Service not provided on",
  "serviceProvidedOnText": "Service provided on",
  "showArrivalOnDifference": 0.2,
  "showMap": true,
  "showOnlyTimepoint": false,
  "showRouteTitle": true,
  "showStopCity": false,
  "showStopDescription": false,
  "skipImport": false,
  "sortingAlgorithm": "common",
  "timeFormat": "HH:mm",
  "verbose": true,
  "zipOutput": false
}

P.S.

The new translation options work perfectly

**Comment by brendannee** [comment]
You can control exactly what timetables get created if you add a
`timetables.txt` file to your GTFS - you may need to do that.
https://github.com/blinktaginc/gtfs-to-html#build-timetablestxt

**Comment by mzzntn** [comment]
Solved :)
