### ISSUE TITLE
[BUG] TypeError: Cannot read property "0" of undefined

### ISSUE THREAD

**Issue by dudebrains01** [BlinkTagInc/gtfs-to-html#84]
I am running the latest version of GTFS-to-HTML and am having difficulty with the program.

## Problem
When generating timetables with maps enabled in the config file, I get the following error thrown:
```
 [  TypeError: Cannot read property '0' of undefined

  - main.js:233
    [npm]/[gtfs-to-html]/[@turf]/simplify/main.js:233:25

  - Array.map

  - main.js:232 simplifyLine
    [npm]/[gtfs-to-html]/[@turf]/simplify/main.js:232:35

  - main.js:203 simplifyGeom
    [npm]/[gtfs-to-html]/[@turf]/simplify/main.js:203:35

  - main.js:177
    [npm]/[gtfs-to-html]/[@turf]/simplify/main.js:177:9

  - main.js:486 Object.geomEach
    [npm]/[gtfs-to-html]/[@turf]/meta/main.js:486:21

  - main.js:176 simplify
    [npm]/[gtfs-to-html]/[@turf]/simplify/main.js:176:10

  - geojson-utils.js:33 Object.exports.getTimetableGeoJSON
    [npm]/[gtfs-to-html]/lib/geojson-utils.js:33:10

  - utils.js:856
    [npm]/[gtfs-to-html]/lib/utils.js:856:27

  - async Promise.all

  - utils.js:1070 async Object.exports.getFormattedTimetablePage
    [npm]/[gtfs-to-html]/lib/utils.js:1070:42

  - gtfs-to-html.js:63
    [npm]/[gtfs-to-html]/lib/gtfs-to-html.js:63:29

  - async Promise.all

  - gtfs-to-html.js:62
    [npm]/[gtfs-to-html]/bin/gtfs-to-html.js:62:5

]
 ```

## GTFS Feed
I am using the latest version of the [Transcollines GTFS File](https://github.com/transcollines/GTFS) plus `timetables.txt` and `timetable_pages.txt` which I have included here: [timetable_pages.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5115228/timetable_pages.txt) and [timetables.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5115229/timetables.txt)
## Config
My config is standard and I have specified a valid MapBox token.
## Issue occurence
The issue seems to arise about halfway through the timetable generation process with any feed as long as maps are enabled in the config file.

**Comment by brendannee** [comment]
Thanks for the detailed report.

I pushed version 1.0.1 which resolves this issue with the way geoJSON simplification was happening.

Try it out and let me know if you find any other issues.

**Comment by dudebrains01** [comment]
It works!

Thanks for the quick fix.
