### ISSUE TITLE
[BUG] Incorrect trip "names" in multi-route timetables

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/gtfs-to-html#86]
When generating combined-route timetables, the trip "name" (which should be the `route_short_name` of the trip, is not correct and is always populated by the `route_short_name` of the `route_id` specified in the highest row for that `timetable_id` in `timetables.txt`.

## Expected behaviour
The multi-route timetable should have the trip's `route_short_name` in the header row like this:

| Point de repere | 921 | 923|
| :------------- | :-----: | :-----: |
| Principale Est / Passe-Partout | 05:25 | 05:37 |
| Principale Est / Beurrerie| 05:27 | 05:38 |
| Centre Communautaire Wakefield | 05:36 | 05:54 |

## Current behaviour
The table header does not have the correct trip headers, like this (notice the second trip):
| Point de repere | 921 | 921|
| :------------- | :-----: | :-----: |
| Principale Est / Passe-Partout | 05:25 | 05:37 |
| Principale Est / Beurrerie| 05:27 | 05:38 |
| Centre Communautaire Wakefield | 05:36 | 05:54 |

## Reproducing the error
1. Use GTFS-to-HTML v1.0.1
2. Unzip [transcollines_timetable_gtfs.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5178065/transcollines_timetable_gtfs.zip) into `gtfs/transcollines`
3. Unzip [views_custom_transcollines.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5178067/views_custom_transcollines.zip) into `views/custom/transcollines`
4. Download [config-transcollines.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5178072/config-transcollines.txt) to the GTFS-to-HTML root file.
5. Change the name of `config-transcollines.txt` to `config-transcollines.json`
6. Open `config-transcollines.json` and insert your mapbox token.
7. Run the following command from the GTFS-to-HTML root directory: `GTFS-to-HTML --configPath config-transcollines.json`
8. Open `html/transcollines/index.html`
9. Select "Corridor La Peche - Chelsea - Gatineau" at the bottom of the timetable list.

Thanks ahead of time!

**Comment by brendannee** [comment]
Thanks for the detailed report. This issue has been resolved in the latest release https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/1.0.2

Don't hesitate to open additional issues or make suggestions and feature requests.
