### ISSUE TITLE
[BUG] Routes do not appear correctly in overview map in index.html

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/gtfs-to-html#87]
In the `index.html` file, the map that should show the routes as they are hovered over in the menu does not show the actual trace of the route on the map, but only the `route_short_name`

## Expected behaviour
When the user hovers over a route link in the `index.html` file, the adjacent map should show the path of the route and it's `route_short_name`

## Current behavior
When the user hovers over a route link in the `index.html` file, the adjacent map only shows the `route_short_name` of the route along the path of the route, but not the line.

## Reproducing the error
1. Use GTFS-to-HTML v1.0.1
2. Unzip [transcollines_timetable_gtfs.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5178065/transcollines_timetable_gtfs.zip) into `gtfs/transcollines`
3. Unzip [views_custom_transcollines.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5178067/views_custom_transcollines.zip) into `views/custom/transcollines`
4. Download [config-transcollines.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5178072/config-transcollines.txt) to the GTFS-to-HTML root file.
5. Change the name of `config-transcollines.txt` to `config-transcollines.json`
6. Open `config-transcollines.json` and insert your mapbox token.
7. Run the following command from the GTFS-to-HTML root directory: `GTFS-to-HTML --configPath config-transcollines.json`
8. Open `html/transcollines/index.html`
9. Hover over any of the timetables in the menu.

Thanks ahead of time!

**Comment by brendannee** [comment]
Thanks for the detailed report. This issue has been resolved in the latest release https://github.com/BlinkTagInc/gtfs-to-html/releases/tag/1.0.2

Don't hesitate to open additional issues or make suggestions and feature requests.

**Comment by brodyFlannigan** [comment]
Fantastic! Thanks for the quick fix.

Keep making cool GTFS gizmos that make my life that much easier.
