### ISSUE TITLE
TimeTable Div is not showing

### ISSUE THREAD

**Issue by 471Q** [BlinkTagInc/gtfs-to-html#88]
Following the documentation from the GTFS-to-HTML website quick guide, and copying views/timetables from this Github repo, I was able to generate the map, but the timetable chart is not being generated, I checked for error the console throws this error 

Uncaught Error: Syntax error, unrecognized expression: #timetable_id_12726|0000001|0 table
    at Function.se.error (jquery.js:566)
    at se.tokenize (jquery.js:989)
    at se.select (jquery.js:1044)
    at Function.se [as find] (jquery.js:299)
    at S.fn.init.find (jquery.js:1158)
    at new S.fn.init (jquery.js:1179)
    at S (jquery.js:55)
    at r.<anonymous> (timetable-map.js:203)
    at r.zt.fire (evented.js:119)
    at r._render (map.js:2478)

I am stuck here, any help is highly appreciated!
![error](https://user-images.githubusercontent.com/35986840/92995072-8b274d00-f532-11ea-98a3-4d461f9f7e20.PNG)

**Comment by 471Q** [comment]
The additional time table files are missing

**Comment by brendannee** [comment]
Thanks for reporting this issue.

For the js error from the map - this was due to the "|" character being in a timetable id. I pushed an update to GTFS-to-HTML version 1.0.5 which should solve this - try it out.

For the fact that the timetable isn't showing up - can you send me a link to the GTFS file you are working with so I can check it out?

**Comment by 471Q** [comment]
Thank you for looking it up! 
I am using this data https://dipl.nt.gov.au/data-feeds/bus-gtfs/google-transit-new.zip 
I noticed the additional files for timetables are missing, I am trying to create a sample batch myself.

**Comment by brendannee** [comment]
Thanks for sharing the feed.

I pushed another update to version 1.0.6 to better handle GTFS without timetables.txt and timetable_pages.txt.

If you run your GTFS and have `showOnlyTimepoint` set to `false` in your `config.json` you'll see times.

You still will likely want to add timetables.txt so you can have better control over which timetables are generated, and you may want timetable_pages.txt so you can group timetables together on the same page.

**Comment by 471Q** [comment]
I have tried your latest update, it fixed the error but even with showOnlyTimepoint set to false, the time table is not being generated.

**Comment by 471Q** [comment]
Were you able to generate a time table with the gtfs feed I gave link to?
