### ISSUE TITLE
TimeTable #FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by 471Q** [BlinkTagInc/gtfs-to-html#91]
Hello, 
I have created the timetable.txt and timetable_stop_order.txt files and generated the HTML, I have total of 8700+ .html files to be generated, I think I messed up with the additional file. The .html file generated for timetable seems to be repeated multiple time for the same route and all of the 4000+ files are mon-fri only. after generating 4100 the cmd stopped working with the FATAL Error.

Any help is highly appreciated. 

Thank you.

**Comment by brendannee** [comment]
Be sure the file is named `timetables.txt`. Try first with only one timetable in timetables.txt to  see if it generates things correctly.

**Comment by 471Q** [comment]
Actually I think the way I made the timetable.txt file is wrong. I just tried only the timetable.txt still it starts generating an 8780 timetable file. Following the documentation, I used python to join different .txt files with trip_id, route_id etc. In the documentation you did not mention any need for joining anything. But I am confused If I'm not joining different table with the foreign keys then how should I create the timetable.txt file

P.S: if I don't use any additional file only 232 timetable .html files are created

**Comment by brendannee** [comment]
Be sure your file is named `timetables.txt` not `timetable.txt` (note the `s`). Can you share your GTFS and your additional timetables.txt and timetable_stop_order.txt files with me?

**Comment by 471Q** [comment]
here is the whole folder, including the two additional files. 
[gtfs.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5257587/gtfs.zip)

just in case you want to see how I created the additional file, here is the python notebook 

[htfs-to-additional.zip](https://github.com/BlinkTagInc/gtfs-to-html/files/5257598/htfs-to-additional.zip)

**Comment by brendannee** [comment]
In your `timetables.txt` file I see many duplicate rows. Each  row should be a unique route_id/direction_id/day-of-week combination - no need to duplicate.


For instance, the  first 15 rows are identical:

0,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
1,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
2,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
3,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
4,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
5,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
6,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
7,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
8,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
9,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
10,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
11,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
12,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
13,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
14,13095,0,20200629,20201129,1,1,1,1,1,0,0,2
15,13095,0,20200629,20201129,1,1,1,1,1,0,0,2

Once you get timetables.txt deduplicated, it should generate many fewer timetables and probably not run out of memory.

Also note that info in `timetable_stop_order.txt` is optional  - for routes where all trips serve the exact same set of  stops you don't need anything  in that file. It is only needed for routes  where some trips  serve a completely different set of stops than others so you can specify  the order of the stops that you'd like to appear in the timetable.

**Comment by 471Q** [comment]
Okay, I'll try to create the timetable.txt again making everything unique.

**Comment by brendannee** [comment]
I pushed an update to the documentation  to better explain the purpose of `timetable_stop_order.txt` file https://gtfstohtml.com/docs/timetable-stop-order. Check it out and let me know if you have suggestions for how to make it easier to understand.

**Comment by 471Q** [comment]
Yes, the updated documentation is much more comprehensible. 
One more thing should mention on the timetable.txt file page is that, that .txt file alone is enough to generate the timetables.

**Comment by brendannee** [comment]
Closing  this issue - feel free to reopen or comment as needed.
