### ISSUE TITLE
Request: Configuration option to skip empty timetables

### ISSUE THREAD

**Issue by NomeQ** [BlinkTagInc/gtfs-to-html#97]
We have a number of agencies that have had frequent schedule changes (and cancellations) and use a heavily customized timetables.txt file. Our support team has noted that it can be tricky to track down every timetable that needs to get removed (say, Sunday service is suddenly canceled on a handful of routes).

It would be useful to have a configuration option to just skip timetables without service, even if they are present in timetables.txt, rather than generating empty tables.

**Comment by brodyFlannigan** [comment]
> We have a number of agencies that have had frequent schedule changes (and cancellations) and use a heavily customized timetables.txt file. Our support team has noted that it can be tricky to track down every timetable that needs to get removed (say, Sunday service is suddenly canceled on a handful of routes).
> 
> It would be useful to have a configuration option to just skip timetables without service, even if they are present in timetables.txt, rather than generating empty tables.

+1 on that. It would be very handy.

**Comment by brendannee** [comment]
Great idea.

I pushed version 1.2 which adds a `allowEmptyTimetables` config option which defaults to `false` (so you don't need to  update your config and by default empty timetables will be skipped. Try it out and let me know if this works as expected.
