### ISSUE TITLE
duplicate stops generating too many stop times

### ISSUE THREAD

**Issue by evantrillium** [BlinkTagInc/gtfs-to-html#99]
Here's a fun one!
RFTA has a route that does a bit of a loop midway through on a few runs. At the start and end of the mini-loop, the same stop is used, and it has stop times both in and out of the loop. Because not all runs do the extra loop, I don't want arr/dep values for all trips at that stop (since most arr/dep will be identical), and in the GTFS I've defined which of the two stop times should be the timepoint. In timetable_stop_order I have included the stop once.

http://data.trilliumtransit.com/gtfs/rfta-co-us/rfta-co-us--ttable.zip

Affected tables are for the "L" route. We've tried using a couple different versions of G2H and every time we get extra stop values in the table
<img width="902" alt="Screen Shot 2020-11-17 at 11 44 43 AM" src="https://user-images.githubusercontent.com/31700284/99466696-b98a2580-28f1-11eb-82af-ac9d3a6e9493.png">

The result is that the extra stop time in the first run pushes all subsequent runs off, and then the last few runs stretch it out even further

Can you take a look at that GTFS and timetables files and let me know what you find? The attached is with an older version of G2H, but newer versions produce the same effect. showOnlyTimepoint doesn't seem to have an effect.

[3930_l_0_mon-sun.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/5556976/3930_l_0_mon-sun.txt)

**Comment by brendannee** [comment]
Thats an interesting case.

I  pushed an update version 1.3.2 which solves this (specifically this commit https://github.com/BlinkTagInc/gtfs-to-html/commit/517dc312ec6070c85d36b2895df84e9e1bbef514 )

Try it out and let me know if there are any issues.
